fn usage_details(node: &Node) -> String {
    const DETAIL_KEYS: &[(&str, &str)] = &[
        ("model", "model"),
        ("vendor", "vendor"),
        ("transport", "transport"),
        ("rotational", "rotational"),
        ("md.uuid", "md-uuid"),
        ("scsi.address", "scsi-address"),
        ("scsi.host", "scsi-host"),
        ("scsi.channel", "scsi-channel"),
        ("scsi.target", "scsi-target"),
        ("scsi.lun", "scsi-lun"),
        ("scsi.peripheral-type", "scsi-type"),
        ("scsi.vendor", "scsi-vendor"),
        ("scsi.model", "scsi-model"),
        ("scsi.revision", "scsi-revision"),
        ("scsi.block-device", "scsi-block"),
        ("scsi.generic-device", "scsi-generic"),
        ("scsi.size", "scsi-size"),
        ("scsi.transport", "scsi-transport"),
        ("scsi.unit-name", "scsi-unit"),
        ("scsi.by-id", "scsi-by-id"),
        ("scsi.wwn", "scsi-wwn"),
        ("scsi.state", "scsi-state"),
        ("scsi.queue-depth", "scsi-queue-depth"),
        ("scsi.queue-type", "scsi-queue-type"),
        ("scsi.scsi-level", "scsi-level"),
        ("scsi.timeout", "scsi-timeout"),
        ("smartctl.svn-revision", "smart-svn"),
        ("smartctl.platform", "smart-platform"),
        ("smartctl.exit-status", "smart-exit-status"),
        ("smartctl.device-name", "smart-device-name"),
        ("smartctl.health.passed", "smart-health-passed"),
        ("smartctl.device-type", "smart-device-type"),
        ("smartctl.protocol", "smart-protocol"),
        ("smartctl.model", "smart-model"),
        ("smartctl.model-family", "smart-family"),
        ("smartctl.vendor", "smart-vendor"),
        ("smartctl.product", "smart-product"),
        ("smartctl.revision", "smart-revision"),
        ("smartctl.firmware-version", "smart-firmware"),
        ("smartctl.serial", "smart-serial"),
        ("smartctl.wwn-naa", "smart-wwn-naa"),
        ("smartctl.wwn-oui", "smart-wwn-oui"),
        ("smartctl.wwn-id", "smart-wwn-id"),
        ("smartctl.user-capacity-bytes", "smart-capacity"),
        ("smartctl.logical-block-size", "smart-logical-block"),
        ("smartctl.physical-block-size", "smart-physical-block"),
        ("smartctl.rotation-rate-rpm", "smart-rpm"),
        ("smartctl.form-factor", "smart-form-factor"),
        ("smartctl.sata-version", "sata-version"),
        (
            "smartctl.interface-speed-current",
            "interface-speed-current",
        ),
        ("smartctl.interface-speed-max", "interface-speed-max"),
        ("smartctl.power-on-hours", "smart-power-on-hours"),
        ("smartctl.power-cycle-count", "smart-power-cycles"),
        (
            "smartctl.temperature-current-celsius",
            "smart-temperature-c",
        ),
        (
            "smartctl.temperature-highest-celsius",
            "smart-temperature-highest-c",
        ),
        (
            "smartctl.temperature-lowest-celsius",
            "smart-temperature-lowest-c",
        ),
        (
            "smartctl.offline-data-collection-status",
            "smart-offline-status",
        ),
        ("smartctl.self-test-status", "smart-self-test"),
        ("smartctl.error-log-summary-count", "smart-error-log-count"),
        ("smartctl.self-test-log-count", "smart-self-test-count"),
        ("smartctl.error-logging-supported", "smart-error-logging"),
        ("smartctl.gp-logging-supported", "smart-gp-logging"),
        ("smartctl.sct-capabilities", "smart-sct-capabilities"),
        (
            "smartctl.scsi-grown-defect-list",
            "smart-scsi-grown-defects",
        ),
        (
            "smartctl.attribute.reallocated-sector-ct.raw",
            "reallocated-sectors",
        ),
        (
            "smartctl.attribute.reallocated-sector-ct.value",
            "reallocated-value",
        ),
        (
            "smartctl.attribute.reallocated-sector-ct.worst",
            "reallocated-worst",
        ),
        (
            "smartctl.attribute.reallocated-sector-ct.threshold",
            "reallocated-threshold",
        ),
        (
            "smartctl.attribute.reallocated-sector-ct.when-failed",
            "reallocated-failed",
        ),
        (
            "smartctl.attribute.current-pending-sector.raw",
            "pending-sectors",
        ),
        (
            "smartctl.attribute.current-pending-sector.value",
            "pending-value",
        ),
        (
            "smartctl.attribute.current-pending-sector.worst",
            "pending-worst",
        ),
        (
            "smartctl.attribute.current-pending-sector.threshold",
            "pending-threshold",
        ),
        (
            "smartctl.attribute.current-pending-sector.when-failed",
            "pending-failed",
        ),
        (
            "smartctl.attribute.offline-uncorrectable.raw",
            "offline-uncorrectable",
        ),
        (
            "smartctl.attribute.offline-uncorrectable.value",
            "offline-uncorrectable-value",
        ),
        (
            "smartctl.attribute.offline-uncorrectable.worst",
            "offline-uncorrectable-worst",
        ),
        (
            "smartctl.attribute.offline-uncorrectable.threshold",
            "offline-uncorrectable-threshold",
        ),
        (
            "smartctl.attribute.offline-uncorrectable.when-failed",
            "offline-uncorrectable-failed",
        ),
        ("nvme.generic-path", "generic"),
        ("nvme.model", "nvme-model"),
        ("nvme.product", "product"),
        ("nvme.firmware", "firmware"),
        ("nvme.index", "ns-index"),
        ("nvme.namespace", "namespace"),
        ("nvme.namespace-id", "nsid"),
        ("nvme.namespace-uuid", "ns-uuid"),
        ("nvme.eui64", "eui64"),
        ("nvme.nguid", "nguid"),
        ("nvme.subsystem", "subsystem"),
        ("nvme.subsystem-name", "subsystem-name"),
        ("nvme.subsystem-nqn", "subsystem-nqn"),
        ("nvme.hostnqn", "hostnqn"),
        ("nvme.controller", "controller"),
        ("nvme.address", "address"),
        ("nvme.transport", "transport"),
        ("nvme.traddr", "traddr"),
        ("nvme.trsvcid", "trsvcid"),
        ("nvme.host-traddr", "host-traddr"),
        ("nvme.host-iface", "host-iface"),
        ("nvme.path-state", "path-state"),
        ("nvme.controller-id", "controller-id"),
        ("nvme.namespace-capacity", "namespace-capacity"),
        ("nvme.lba-format", "lba-format"),
        ("nvme.maximum-lba", "max-lba"),
        ("nvme.sector-size", "sector-size"),
        ("nvme.ana-state", "ana-state"),
        ("nvme.formatted-lba-index", "flba-index"),
        ("nvme.formatted-lba-data-size", "flba-data"),
        ("nvme.formatted-lba-metadata-size", "flba-metadata"),
        (
            "nvme.formatted-lba-relative-performance",
            "flba-relative-performance",
        ),
        ("nvme.id-ns.nsze", "nsze"),
        ("nvme.id-ns.ncap", "ncap"),
        ("nvme.id-ns.nuse", "nuse"),
        ("nvme.id-ns.nsfeat", "nsfeat"),
        ("nvme.id-ns.nlbaf", "nlbaf"),
        ("nvme.id-ns.flbas", "flbas"),
        ("nvme.id-ns.mc", "mc"),
        ("nvme.id-ns.dpc", "dpc"),
        ("nvme.id-ns.dps", "dps"),
        ("nvme.id-ns.nmic", "nmic"),
        ("nvme.id-ns.rescap", "rescap"),
        ("nvme.id-ns.fpi", "fpi"),
        ("nvme.id-ns.dlfeat", "dlfeat"),
        ("nvme.id-ns.nawun", "nawun"),
        ("nvme.id-ns.nawupf", "nawupf"),
        ("nvme.id-ns.nacwu", "nacwu"),
        ("nvme.id-ns.nabsn", "nabsn"),
        ("nvme.id-ns.nabo", "nabo"),
        ("nvme.id-ns.nabspf", "nabspf"),
        ("nvme.id-ns.noiob", "noiob"),
        ("nvme.id-ns.nvmcap", "nvmcap"),
        ("nvme.id-ctrl.vid", "vid"),
        ("nvme.id-ctrl.ssvid", "ssvid"),
        ("nvme.id-ctrl.rab", "rab"),
        ("nvme.id-ctrl.ieee", "ieee"),
        ("nvme.id-ctrl.cmic", "cmic"),
        ("nvme.id-ctrl.mdts", "mdts"),
        ("nvme.id-ctrl.version", "version"),
        ("nvme.id-ctrl.controller-type", "controller-type"),
        ("nvme.id-ctrl.oacs", "optional-admin-commands"),
        ("nvme.id-ctrl.fuses", "fused-operations"),
        ("nvme.id-ctrl.fna", "format-nvm-attributes"),
        ("nvme.id-ctrl.awun", "atomic-write-unit-normal"),
        ("nvme.id-ctrl.awupf", "atomic-write-unit-powerfail"),
        ("nvme.id-ctrl.acwu", "atomic-compare-write-unit"),
        ("nvme.id-ctrl.sgls", "sgl-support"),
        ("nvme.id-ctrl.namespace-set-id-max", "namespace-set-id-max"),
        (
            "nvme.id-ctrl.endurance-group-id-max",
            "endurance-group-id-max",
        ),
        ("nvme.id-ctrl.ana-transition-time", "ana-transition-time"),
        ("nvme.id-ctrl.ana-group-max", "ana-group-max"),
        (
            "nvme.id-ctrl.persistent-event-log-size",
            "persistent-event-log-size",
        ),
        ("nvme.id-ctrl.domain-id", "domain-id"),
        (
            "nvme.id-ctrl.warning-composite-temp",
            "warning-composite-temp",
        ),
        (
            "nvme.id-ctrl.critical-composite-temp",
            "critical-composite-temp",
        ),
        (
            "nvme.id-ctrl.minimum-thermal-management-temp",
            "min-thermal-management-temp",
        ),
        (
            "nvme.id-ctrl.maximum-thermal-management-temp",
            "max-thermal-management-temp",
        ),
        ("nvme.id-ctrl.total-nvm-capacity", "total-nvm-capacity"),
        (
            "nvme.id-ctrl.unallocated-nvm-capacity",
            "unallocated-nvm-capacity",
        ),
        ("nvme.id-ctrl.namespace-count", "namespace-count"),
        ("nvme.id-ctrl.oncs", "oncs"),
        ("nvme.id-ctrl.volatile-write-cache", "volatile-write-cache"),
        (
            "nvme.id-ctrl.sanitize-capabilities",
            "sanitize-capabilities",
        ),
        ("nvme.id-ctrl.ana-capabilities", "ana-capabilities"),
        ("nvme.smart.critical-warning", "critical-warning"),
        ("nvme.smart.temperature-kelvin", "temperature-k"),
        (
            "nvme.smart.available-spare-percent",
            "available-spare-percent",
        ),
        (
            "nvme.smart.spare-threshold-percent",
            "spare-threshold-percent",
        ),
        ("nvme.smart.percent-used", "percent-used"),
        ("nvme.smart.data-units-read", "data-units-read"),
        ("nvme.smart.data-units-written", "data-units-written"),
        ("nvme.smart.host-read-commands", "host-read-commands"),
        ("nvme.smart.host-write-commands", "host-write-commands"),
        ("nvme.smart.controller-busy-time", "controller-busy-time"),
        ("nvme.smart.power-cycles", "power-cycles"),
        ("nvme.smart.power-on-hours", "power-on-hours"),
        ("nvme.smart.unsafe-shutdowns", "unsafe-shutdowns"),
        ("nvme.smart.media-errors", "media-errors"),
        ("nvme.smart.error-log-entries", "error-log-entries"),
        ("nvme.smart.warning-temperature-time", "warning-temp-time"),
        (
            "nvme.smart.critical-composite-temperature-time",
            "critical-temp-time",
        ),
        ("nvme.smart.temperature-sensor-1-kelvin", "temp-sensor-1-k"),
        ("nvme.smart.temperature-sensor-2-kelvin", "temp-sensor-2-k"),
        ("nvme.smart.temperature-sensor-3-kelvin", "temp-sensor-3-k"),
        ("nvme.smart.temperature-sensor-4-kelvin", "temp-sensor-4-k"),
        ("nvme.smart.temperature-sensor-5-kelvin", "temp-sensor-5-k"),
        ("nvme.smart.temperature-sensor-6-kelvin", "temp-sensor-6-k"),
        ("nvme.smart.temperature-sensor-7-kelvin", "temp-sensor-7-k"),
        ("nvme.smart.temperature-sensor-8-kelvin", "temp-sensor-8-k"),
        (
            "nvme.smart.thermal-temp1-transition-count",
            "thermal-temp1-transitions",
        ),
        (
            "nvme.smart.thermal-temp2-transition-count",
            "thermal-temp2-transitions",
        ),
        (
            "nvme.smart.thermal-temp1-total-time",
            "thermal-temp1-total-time",
        ),
        (
            "nvme.smart.thermal-temp2-total-time",
            "thermal-temp2-total-time",
        ),
        ("lsblk.type", "lsblk-type"),
        ("lsblk.logical-sector-size", "logical-sector"),
        ("lsblk.physical-sector-size", "physical-sector"),
        ("lsblk.minimum-io-size", "minimum-io"),
        ("lsblk.optimal-io-size", "optimal-io"),
        ("lsblk.discard-alignment", "discard-alignment"),
        ("lsblk.discard-granularity", "discard-granularity"),
        ("lsblk.discard-max", "discard-max"),
        ("lsblk.discard-zeroes-data", "discard-zeroes"),
        ("lsblk.scheduler", "scheduler"),
        ("lsblk.request-queue-size", "rq-size"),
        ("lsblk.write-same-max", "write-same-max"),
        ("lsblk.zoned", "zoned"),
        ("lsblk.zone-size", "zone-size"),
        ("lsblk.zone-write-granularity", "zone-write-granularity"),
        ("lsblk.zone-append-max", "zone-append-max"),
        ("lsblk.zone-count", "zone-count"),
        ("lsblk.zone-open-max", "zone-open-max"),
        ("lsblk.zone-active-max", "zone-active-max"),
        ("lsblk.dax", "dax"),
        ("lsblk.hotplug", "hotplug"),
        ("filesystem.type", "fstype"),
        ("blkid.type", "blkid-type"),
        ("blkid.version", "version"),
        ("blkid.block-size", "blkid-block-size"),
        ("blkid.usage", "usage"),
        ("blkid.uuid-sub", "uuid-sub"),
        ("blkid.partlabel", "partlabel"),
        ("partition.table", "ptable"),
        ("partition.number", "partno"),
        ("partition.start", "start"),
        ("partition.start-bytes", "start-bytes"),
        ("partition.end", "end"),
        ("partition.end-bytes", "end-bytes"),
        ("partition.type", "type"),
        ("partition.name", "part-name"),
        ("partition.flags", "flags"),
        ("partition.disk-flags", "disk-flags"),
        ("parted.transport", "parted-transport"),
        ("parted.logical-sector-size", "logical-sector"),
        ("parted.physical-sector-size", "physical-sector"),
        ("swap.active", "swap-active"),
        ("swap.type", "swap-type"),
        ("swap.priority", "swap-priority"),
        ("zram.algorithm", "zram-algorithm"),
        ("zram.streams", "zram-streams"),
        ("zram.disksize", "zram-disksize"),
        ("zram.data", "zram-data"),
        ("zram.compressed", "zram-compressed"),
        ("zram.total", "zram-total"),
        ("zram.memory-limit", "zram-memory-limit"),
        ("zram.memory-used", "zram-memory-used"),
        ("zram.memory-peak", "zram-memory-peak"),
        ("zram.zero-pages", "zram-zero-pages"),
        ("zram.migrated", "zram-migrated"),
        ("zram.compression-ratio", "zram-ratio"),
        ("zram.mountpoint", "zram-mountpoint"),
        ("zram.swap", "zram-swap"),
        ("loop.backing", "loop-backing"),
        ("loop.back-file", "back-file"),
        ("loop.backing-inode", "back-ino"),
        ("loop.backing-major-minor", "back-major-minor"),
        ("loop.major-minor", "major-minor"),
        ("loop.offset", "offset"),
        ("loop.sizelimit", "sizelimit"),
        ("loop.logical-sector-size", "logical-sector"),
        ("loop.autoclear", "autoclear"),
        ("loop.partscan", "partscan"),
        ("loop.read-only", "ro"),
        ("loop.direct-io", "dio"),
        ("udev.symlink", "udev-link"),
        ("udev.devpath", "udev-devpath"),
        ("udev.devname", "udev-devname"),
        ("udev.devtype", "udev-devtype"),
        ("udev.id-fs-type", "udev-fstype"),
        ("udev.id-fs-version", "udev-fs-version"),
        ("udev.id-fs-usage", "udev-fs-usage"),
        ("udev.id-fs-uuid", "udev-fs-uuid"),
        ("udev.id-fs-uuid-enc", "udev-fs-uuid-enc"),
        ("udev.id-fs-uuid-sub", "udev-fs-uuid-sub"),
        ("udev.id-fs-label", "udev-label"),
        ("udev.id-fs-label-enc", "udev-label-enc"),
        ("udev.id-fs-label-safe", "udev-label-safe"),
        ("udev.id-fs-block-size", "udev-fs-block-size"),
        ("udev.id-fs-lastblock", "udev-fs-lastblock"),
        ("udev.id-bus", "udev-bus"),
        ("udev.id-type", "udev-type"),
        ("udev.id-model", "udev-model"),
        ("udev.id-model-id", "udev-model-id"),
        ("udev.id-vendor", "udev-vendor"),
        ("udev.id-vendor-id", "udev-vendor-id"),
        ("udev.id-revision", "udev-revision"),
        ("udev.id-serial", "udev-serial"),
        ("udev.id-serial-short", "udev-serial-short"),
        ("udev.id-wwn", "udev-wwn"),
        ("udev.id-path", "udev-path"),
        ("udev.id-path-tag", "udev-path-tag"),
        ("udev.id-part-entry-disk", "udev-part-disk"),
        ("udev.id-part-entry-number", "udev-part-number"),
        ("udev.id-part-entry-offset", "udev-part-offset"),
        ("udev.id-part-entry-size", "udev-part-size"),
        ("udev.id-part-entry-scheme", "udev-part-scheme"),
        ("udev.id-part-entry-type", "udev-part-type"),
        ("udev.id-part-entry-name", "udev-part-name"),
        ("udev.id-part-entry-uuid", "udev-part-uuid"),
        ("udev.id-part-entry-flags", "udev-part-flags"),
        ("udev.id-part-table-type", "udev-table-type"),
        ("udev.id-part-table-uuid", "udev-table-uuid"),
        ("udev.dm-name", "dm-name"),
        ("udev.dm-uuid", "dm-uuid"),
        ("udev.dm-vg-name", "dm-vg"),
        ("udev.dm-lv-name", "dm-lv"),
        ("udev.dm-udev-rules-vsn", "dm-rules"),
        ("udev.dm-udev-primary-source-flag", "dm-primary-source"),
        (
            "udev.dm-udev-disable-other-rules-flag",
            "dm-disable-other-rules",
        ),
        ("udev.dm-subsystem-udev-flag0", "dm-subsystem-flag0"),
        ("udev.dm-subsystem-udev-flag1", "dm-subsystem-flag1"),
        ("udev.major", "major"),
        ("udev.minor", "minor"),
        ("udev.subsystem", "subsystem"),
        ("lvm.data-percent", "data"),
        ("lvm.metadata-percent", "metadata"),
        ("lvm.snap-percent", "snap"),
        ("lvm.copy-percent", "copy"),
        ("lvm.sync-percent", "sync"),
        ("lvm.attr", "attr"),
        ("lvm.layout", "layout"),
        ("lvm.segment-type", "segment-type"),
        ("lvm.segment-stripes", "stripes"),
        ("lvm.segment-data-stripes", "data-stripes"),
        ("lvm.reshape-length", "reshape-length"),
        ("lvm.reshape-length-extents", "reshape-extents"),
        ("lvm.data-copies", "data-copies"),
        ("lvm.data-offset", "data-offset"),
        ("lvm.new-data-offset", "new-data-offset"),
        ("lvm.parity-chunks", "parity-chunks"),
        ("lvm.stripe-size", "stripe-size"),
        ("lvm.region-size", "region-size"),
        ("lvm.segment-start", "segment-start"),
        ("lvm.segment-start-extent", "segment-start-pe"),
        ("lvm.segment-size", "segment-size"),
        ("lvm.segment-size-extents", "segment-size-pe"),
        ("lvm.segment-tags", "segment-tags"),
        ("lvm.chunk-size", "chunk-size"),
        ("lvm.thin-count", "thin-count"),
        ("lvm.discards", "discards"),
        ("lvm.zero", "zero"),
        ("lvm.transaction-id", "transaction-id"),
        ("lvm.thin-id", "thin-id"),
        ("lvm.devices", "devices"),
        ("lvm.metadata-devices", "metadata-devices"),
        ("lvm.segment-pe-ranges", "pe-ranges"),
        ("lvm.segment-le-ranges", "le-ranges"),
        ("lvm.segment-metadata-le-ranges", "metadata-le-ranges"),
        ("lvm.segment-monitor", "segment-monitor"),
        ("lvm.cache-metadata-format", "cache-metadata-format"),
        ("lvm.segment-cache-mode", "segment-cache-mode"),
        ("lvm.segment-cache-policy", "segment-cache-policy"),
        ("lvm.cache-settings", "cache-settings"),
        ("lvm.integrity-settings", "integrity-settings"),
        ("lvm.vdo-compression", "vdo-compression"),
        ("lvm.vdo-deduplication", "vdo-deduplication"),
        ("lvm.vdo-minimum-io-size", "vdo-min-io"),
        ("lvm.vdo-block-map-cache-size", "vdo-block-map-cache"),
        ("lvm.vdo-block-map-era-length", "vdo-block-map-era"),
        ("lvm.vdo-use-sparse-index", "vdo-sparse-index"),
        ("lvm.vdo-index-memory-size", "vdo-index-memory"),
        ("lvm.vdo-slab-size", "vdo-slab"),
        ("lvm.vdo-ack-threads", "vdo-ack-threads"),
        ("lvm.vdo-bio-threads", "vdo-bio-threads"),
        ("lvm.vdo-bio-rotation", "vdo-bio-rotation"),
        ("lvm.vdo-cpu-threads", "vdo-cpu-threads"),
        ("lvm.vdo-hash-zone-threads", "vdo-hash-zone-threads"),
        ("lvm.vdo-logical-threads", "vdo-logical-threads"),
        ("lvm.vdo-physical-threads", "vdo-physical-threads"),
        ("lvm.vdo-max-discard", "vdo-max-discard"),
        ("lvm.vdo-header-size", "vdo-header"),
        ("lvm.vdo-use-metadata-hints", "vdo-metadata-hints"),
        ("lvm.vdo-write-policy", "vdo-write-policy"),
        ("lvm.vdo-operating-mode", "vdo-mode"),
        ("lvm.vdo-compression-state", "vdo-compression-state"),
        ("lvm.vdo-index-state", "vdo-index-state"),
        ("lvm.vdo-used-size", "vdo-used"),
        ("lvm.vdo-saving-percent", "vdo-saving"),
        ("lvm.origin", "origin"),
        ("lvm.pool", "pool"),
        ("lvm.pv-format", "pv-format"),
        ("lvm.dev-size", "dev-size"),
        ("lvm.pv-major", "pv-major"),
        ("lvm.pv-minor", "pv-minor"),
        ("lvm.pe-start", "pe-start"),
        ("lvm.pv-attr", "pv-attr"),
        ("lvm.pv-allocatable", "pv-allocatable"),
        ("lvm.pv-exported", "pv-exported"),
        ("lvm.pv-missing", "pv-missing"),
        ("lvm.pv-pe-count", "pv-extents"),
        ("lvm.pv-pe-allocated", "pv-extents-used"),
        ("lvm.pv-tags", "pv-tags"),
        ("lvm.pv-mda-count", "pv-mda-count"),
        ("lvm.pv-mda-used-count", "pv-mda-used"),
        ("lvm.pv-mda-free", "pv-mda-free"),
        ("lvm.pv-mda-size", "pv-mda-size"),
        ("lvm.pv-bootloader-area-start", "pv-ba-start"),
        ("lvm.pv-bootloader-area-size", "pv-ba-size"),
        ("lvm.pv-in-use", "pv-in-use"),
        ("lvm.pv-duplicate", "pv-duplicate"),
        ("lvm.pv-device-id", "pv-device-id"),
        ("lvm.pv-device-id-type", "pv-device-id-type"),
        ("lvm.vg-format", "vg-format"),
        ("lvm.vg-attr", "vg-attr"),
        ("lvm.vg-extendable", "vg-extendable"),
        ("lvm.vg-exported", "vg-exported"),
        ("lvm.vg-autoactivation", "vg-autoactivation"),
        ("lvm.vg-partial", "vg-partial"),
        ("lvm.allocation-policy", "allocation"),
        ("lvm.vg-clustered", "vg-clustered"),
        ("lvm.vg-shared", "vg-shared"),
        ("lvm.vg-system-id", "system-id"),
        ("lvm.vg-lock-type", "lock-type"),
        ("lvm.vg-lock-args", "lock-args"),
        ("lvm.extent-size", "extent"),
        ("lvm.extent-count", "extents"),
        ("lvm.free-count", "free-extents"),
        ("lvm.max-lvs", "max-lvs"),
        ("lvm.max-pvs", "max-pvs"),
        ("lvm.pv-count", "pvs"),
        ("lvm.missing-pv-count", "missing-pvs"),
        ("lvm.lv-count", "lvs"),
        ("lvm.snapshot-count", "snapshots"),
        ("lvm.vg-seqno", "seqno"),
        ("lvm.vg-profile", "vg-profile"),
        ("lvm.vg-mda-count", "vg-mda-count"),
        ("lvm.vg-mda-used-count", "vg-mda-used"),
        ("lvm.vg-mda-free", "vg-mda-free"),
        ("lvm.vg-mda-size", "vg-mda-size"),
        ("lvm.vg-mda-copies", "vg-mda-copies"),
        ("lvm.active", "active"),
        ("lvm.active-locally", "active-local"),
        ("lvm.active-remotely", "active-remote"),
        ("lvm.active-exclusively", "active-exclusive"),
        ("lvm.permissions", "permissions"),
        ("lvm.health", "health"),
        ("lvm.when-full", "when-full"),
        ("lvm.metadata-size", "metadata-size"),
        ("lvm.tags", "tags"),
        ("lvm.dm-path", "dm-path"),
        ("lvm.parent", "parent"),
        ("lvm.read-ahead", "read-ahead"),
        ("lvm.kernel-read-ahead", "kernel-read-ahead"),
        ("lvm.suspended", "suspended"),
        ("lvm.live-table", "live-table"),
        ("lvm.inactive-table", "inactive-table"),
        ("lvm.modules", "modules"),
        ("lvm.host", "host"),
        ("lvm.historical", "historical"),
        ("lvm.kernel-major", "kernel-major"),
        ("lvm.kernel-minor", "kernel-minor"),
        ("lvm.device-open", "device-open"),
        ("lvm.check-needed", "check-needed"),
        ("lvm.role", "role"),
        ("lvm.time", "time"),
        ("lvm.raid-mismatch-count", "raid-mismatches"),
        ("lvm.raid-sync-action", "raid-sync"),
        ("lvm.raid-write-behind", "raid-write-behind"),
        ("lvm.raid-min-recovery-rate", "raid-min-recovery"),
        ("lvm.raid-max-recovery-rate", "raid-max-recovery"),
        ("lvm.raid-integrity-mode", "raid-integrity"),
        ("lvm.raid-integrity-block-size", "raid-integrity-block"),
        ("lvm.raid-integrity-mismatches", "raid-integrity-mismatches"),
        ("lvm.cache-total-blocks", "cache-total"),
        ("lvm.cache-used-blocks", "cache-used"),
        ("lvm.cache-dirty-blocks", "cache-dirty"),
        ("lvm.cache-read-hits", "cache-read-hits"),
        ("lvm.cache-read-misses", "cache-read-misses"),
        ("lvm.cache-write-hits", "cache-write-hits"),
        ("lvm.cache-write-misses", "cache-write-misses"),
        ("lvm.cache-promotions", "cache-promotions"),
        ("lvm.cache-demotions", "cache-demotions"),
        ("lvm.cache-mode", "cache-mode"),
        ("lvm.cache-policy", "cache-policy"),
        ("lvm.kernel-cache-settings", "kernel-cache-settings"),
        ("lvm.kernel-cache-mode", "kernel-cache-mode"),
        ("lvm.kernel-cache-policy", "kernel-cache-policy"),
        ("lvm.kernel-metadata-format", "kernel-metadata-format"),
        ("lvm.kernel-discards", "kernel-discards"),
        ("lvm.writecache-total-blocks", "writecache-total"),
        ("lvm.writecache-free-blocks", "writecache-free"),
        ("lvm.writecache-writeback-blocks", "writecache-writeback"),
        ("lvm.writecache-block-size", "writecache-block-size"),
        ("lvm.writecache-error", "writecache-error"),
        ("btrfs.qgroup-id", "qgroup"),
        ("btrfs.qgroup-parents", "qgroup-parents"),
        ("btrfs.qgroup-children", "qgroup-children"),
        ("btrfs.mount-target", "mount-target"),
        ("btrfs.device-id", "device-id"),
        ("btrfs.device-stat-write-io-errs", "write-io-errs"),
        ("btrfs.device-stat-read-io-errs", "read-io-errs"),
        ("btrfs.device-stat-flush-io-errs", "flush-io-errs"),
        ("btrfs.device-stat-corruption-errs", "corruption-errs"),
        ("btrfs.device-stat-generation-errs", "generation-errs"),
        ("btrfs.id", "subvol-id"),
        ("btrfs.generation", "generation"),
        ("btrfs.created-generation", "created-generation"),
        ("btrfs.parent-id", "parent-id"),
        ("btrfs.top-level", "top-level"),
        ("btrfs.parent-uuid", "parent-uuid"),
        ("btrfs.received-uuid", "received-uuid"),
        ("btrfs.data-profile", "data-profile"),
        ("btrfs.data-size", "data-size"),
        ("btrfs.data-used", "data-used"),
        ("btrfs.metadata-profile", "metadata-profile"),
        ("btrfs.metadata-size", "metadata-size"),
        ("btrfs.metadata-used", "metadata-used"),
        ("btrfs.system-profile", "system-profile"),
        ("btrfs.system-size", "system-size"),
        ("btrfs.system-used", "system-used"),
        ("btrfs.max-referenced", "max-rfer"),
        ("btrfs.max-exclusive", "max-excl"),
        ("vdo.storage-device", "backing"),
        ("vdo.logical-size", "logical"),
        ("vdo.physical-size", "physical"),
        ("vdo.stats-size", "stats-size"),
        ("vdo.stats-used", "stats-used"),
        ("vdo.stats-available", "stats-free"),
        ("vdo.use-percent", "vdo-use"),
        ("vdo.space-saving-percent", "saving"),
        ("vdo.operating-mode", "mode"),
        ("vdo.recovery-percentage", "recovery"),
        ("vdo.write-policy", "write-policy"),
        ("vdo.configured-write-policy", "configured-write-policy"),
        ("vdo.index-memory-setting", "index-memory"),
        ("vdo.block-map-cache-size", "block-map-cache"),
        ("vdo.compression", "compression"),
        ("vdo.deduplication", "deduplication"),
        ("vdo.version", "vdo-version"),
        ("vdo.release-version", "vdo-release"),
        ("vdo.data-blocks-used", "data-blocks"),
        ("vdo.data-blocks-used-bytes", "data-bytes"),
        ("vdo.overhead-blocks-used", "overhead-blocks"),
        ("vdo.overhead-blocks-used-bytes", "overhead-bytes"),
        ("vdo.logical-blocks-used", "logical-blocks"),
        ("vdo.logical-blocks-used-bytes", "logical-bytes"),
        ("dm.name", "dm-name"),
        ("dm.uuid", "dm-uuid"),
        ("dm.major", "dm-major"),
        ("dm.minor", "dm-minor"),
        ("dm.open-count", "open"),
        ("dm.segments", "segments"),
        ("dm.events", "events"),
        ("dm.table.targets", "dm-table-targets"),
        ("dm.table.segment-count", "dm-table-segments"),
        ("dm.table.segment.0.start", "dm-table-start"),
        ("dm.table.segment.0.length", "dm-table-length"),
        ("dm.table.segment.0.target", "dm-table-target"),
        ("dm.table.segment.0.payload", "dm-table-payload"),
        ("dm.table.segment.0.device", "dm-table-device"),
        ("dm.table.segment.0.offset", "dm-table-offset"),
        (
            "dm.table.segment.0.metadata-device",
            "dm-table-metadata-device",
        ),
        ("dm.table.segment.0.data-device", "dm-table-data-device"),
        (
            "dm.table.segment.0.data-block-size",
            "dm-table-data-block-size",
        ),
        (
            "dm.table.segment.0.low-water-mark",
            "dm-table-low-water-mark",
        ),
        ("dm.table.segment.0.pool-device", "dm-table-pool-device"),
        ("dm.table.segment.0.thin-device-id", "dm-table-thin-id"),
        (
            "dm.table.segment.0.external-origin-device",
            "dm-table-external-origin",
        ),
        ("dm.table.segment.0.cache-device", "dm-table-cache-device"),
        ("dm.table.segment.0.origin-device", "dm-table-origin-device"),
        ("dm.table.segment.0.block-size", "dm-table-block-size"),
        ("dm.table.segment.0.cow-device", "dm-table-cow-device"),
        ("dm.table.segment.0.persistence", "dm-table-persistence"),
        ("dm.table.segment.0.chunk-size", "dm-table-chunk-size"),
        ("dm.table.segment.0.stripe-count", "dm-table-stripes"),
        (
            "dm.table.segment.0.stripe.0.device",
            "dm-table-stripe0-device",
        ),
        (
            "dm.table.segment.0.stripe.0.offset",
            "dm-table-stripe0-offset",
        ),
        (
            "dm.table.segment.0.stripe.1.device",
            "dm-table-stripe1-device",
        ),
        (
            "dm.table.segment.0.stripe.1.offset",
            "dm-table-stripe1-offset",
        ),
        ("dm.table.segment.0.crypt.cipher", "dm-crypt-cipher"),
        ("dm.table.segment.0.crypt.iv-offset", "dm-crypt-iv-offset"),
        ("dm.table.segment.0.crypt.device", "dm-crypt-device"),
        ("dm.table.segment.0.crypt.offset", "dm-crypt-offset"),
        ("dm.status.targets", "dm-status-targets"),
        ("dm.status.segment-count", "dm-status-segments"),
        ("dm.status.segment.0.start", "dm-status-start"),
        ("dm.status.segment.0.length", "dm-status-length"),
        ("dm.status.segment.0.target", "dm-status-target"),
        ("dm.status.segment.0.payload", "dm-status-payload"),
        (
            "dm.status.segment.0.metadata-used-blocks",
            "dm-status-metadata-used",
        ),
        (
            "dm.status.segment.0.metadata-total-blocks",
            "dm-status-metadata-total",
        ),
        (
            "dm.status.segment.0.cache-used-blocks",
            "dm-status-cache-used",
        ),
        (
            "dm.status.segment.0.cache-total-blocks",
            "dm-status-cache-total",
        ),
        (
            "dm.status.segment.0.data-used-blocks",
            "dm-status-data-used",
        ),
        (
            "dm.status.segment.0.data-total-blocks",
            "dm-status-data-total",
        ),
        ("dm.status.segment.0.read-hits", "dm-status-read-hits"),
        ("dm.status.segment.0.read-misses", "dm-status-read-misses"),
        ("dm.status.segment.0.write-hits", "dm-status-write-hits"),
        ("dm.status.segment.0.write-misses", "dm-status-write-misses"),
        ("dm.status.segment.0.dirty-blocks", "dm-status-dirty"),
        ("dm.status.segment.0.mode", "dm-status-mode"),
        ("dm.status.segment.0.used-sectors", "dm-status-used-sectors"),
        (
            "dm.status.segment.0.total-sectors",
            "dm-status-total-sectors",
        ),
        ("cryptsetup.active", "active"),
        ("cryptsetup.in-use", "in-use"),
        ("cryptsetup.cipher", "cipher"),
        ("cryptsetup.mode", "mode"),
        ("cryptsetup.sector-size", "sector-size"),
        ("cryptsetup.sector-count", "sectors"),
        ("cryptsetup.luks-version", "luks"),
        ("cryptsetup.luks-epoch", "epoch"),
        ("cryptsetup.luks-metadata-area", "metadata-area"),
        ("cryptsetup.luks-keyslots-area", "keyslots-area"),
        ("cryptsetup.luks-subsystem", "subsystem"),
        ("cryptsetup.luks-flags", "flags"),
        ("cryptsetup.luks-keyslot-count", "keyslots"),
        ("cryptsetup.luks-token-count", "tokens"),
        ("cryptsetup.luks-keyslots", "keyslot-ids"),
        ("cryptsetup.luks-tokens", "token-ids"),
        ("cryptsetup.luks-keyslot-0-type", "keyslot-0"),
        ("cryptsetup.luks-keyslot-0-priority", "keyslot-0-priority"),
        ("cryptsetup.luks-keyslot-0-cipher", "keyslot-0-cipher"),
        (
            "cryptsetup.luks-keyslot-0-cipher-key",
            "keyslot-0-cipher-key",
        ),
        ("cryptsetup.luks-keyslot-0-pbkdf", "keyslot-0-pbkdf"),
        ("cryptsetup.luks-keyslot-0-time-cost", "keyslot-0-time"),
        ("cryptsetup.luks-keyslot-0-memory", "keyslot-0-memory"),
        ("cryptsetup.luks-keyslot-0-threads", "keyslot-0-threads"),
        ("cryptsetup.luks-keyslot-0-salt", "keyslot-0-salt"),
        (
            "cryptsetup.luks-keyslot-0-af-stripes",
            "keyslot-0-af-stripes",
        ),
        (
            "cryptsetup.luks-keyslot-0-area-offset",
            "keyslot-0-area-offset",
        ),
        (
            "cryptsetup.luks-keyslot-0-area-length",
            "keyslot-0-area-length",
        ),
        ("cryptsetup.luks-keyslot-0-digest-id", "keyslot-0-digest"),
        ("cryptsetup.luks-keyslot-1-type", "keyslot-1"),
        ("cryptsetup.luks-keyslot-1-priority", "keyslot-1-priority"),
        ("cryptsetup.luks-keyslot-1-cipher", "keyslot-1-cipher"),
        (
            "cryptsetup.luks-keyslot-1-cipher-key",
            "keyslot-1-cipher-key",
        ),
        ("cryptsetup.luks-keyslot-1-pbkdf", "keyslot-1-pbkdf"),
        ("cryptsetup.luks-keyslot-1-time-cost", "keyslot-1-time"),
        ("cryptsetup.luks-keyslot-1-memory", "keyslot-1-memory"),
        ("cryptsetup.luks-keyslot-1-threads", "keyslot-1-threads"),
        ("cryptsetup.luks-keyslot-1-salt", "keyslot-1-salt"),
        (
            "cryptsetup.luks-keyslot-1-af-stripes",
            "keyslot-1-af-stripes",
        ),
        (
            "cryptsetup.luks-keyslot-1-area-offset",
            "keyslot-1-area-offset",
        ),
        (
            "cryptsetup.luks-keyslot-1-area-length",
            "keyslot-1-area-length",
        ),
        ("cryptsetup.luks-keyslot-1-digest-id", "keyslot-1-digest"),
        ("cryptsetup.luks-token-0-type", "token-0"),
        ("cryptsetup.luks-token-0-keyslot", "token-0-keyslot"),
        ("cryptsetup.luks-token-0-keyslots", "token-0-keyslots"),
        ("cryptsetup.luks-token-0-tpm2-pcrs", "token-0-tpm2-pcrs"),
        ("cryptsetup.luks-token-0-tpm2-hash", "token-0-tpm2-hash"),
        ("cryptsetup.luks-token-1-type", "token-1"),
        ("cryptsetup.luks-token-1-keyslot", "token-1-keyslot"),
        ("cryptsetup.luks-token-1-keyslots", "token-1-keyslots"),
        ("cryptsetup.luks-token-1-tpm2-pcrs", "token-1-tpm2-pcrs"),
        ("cryptsetup.luks-token-1-tpm2-hash", "token-1-tpm2-hash"),
        ("cryptsetup.luks-digest-count", "digests"),
        ("cryptsetup.luks-digests", "digest-ids"),
        ("cryptsetup.luks-digest-0-type", "digest-0"),
        ("cryptsetup.luks-digest-0-hash", "digest-0-hash"),
        ("cryptsetup.luks-digest-0-iterations", "digest-0-iterations"),
        ("cryptsetup.luks-digest-0-salt", "digest-0-salt"),
        ("cryptsetup.luks-digest-0-digest", "digest-0-digest"),
        ("cryptsetup.luks-digest-1-type", "digest-1"),
        ("cryptsetup.luks-digest-1-hash", "digest-1-hash"),
        ("cryptsetup.luks-digest-1-iterations", "digest-1-iterations"),
        ("cryptsetup.luks-digest-1-salt", "digest-1-salt"),
        ("cryptsetup.luks-digest-1-digest", "digest-1-digest"),
        ("cryptsetup.luks-data-cipher", "data-cipher"),
        ("cryptsetup.luks-data-offset", "data-offset"),
        ("cryptsetup.luks-data-length", "data-length"),
        ("cryptsetup.luks-data-sector", "data-sector"),
        ("multipath.dm", "dm"),
        ("multipath.wwid", "wwid"),
        ("multipath.vendor-product", "vendor"),
        ("multipath.size", "size"),
        ("multipath.features", "features"),
        ("multipath.hwhandler", "handler"),
        ("multipath.write-protect", "wp"),
        ("multipath.host-path", "host-path"),
        ("multipath.scsi-host", "scsi-host"),
        ("multipath.scsi-channel", "scsi-channel"),
        ("multipath.scsi-id", "scsi-id"),
        ("multipath.scsi-lun", "scsi-lun"),
        ("major-minor", "major-minor"),
        ("multipath.group-policy", "group-policy"),
        ("multipath.group-prio", "group-prio"),
        ("multipath.group-status", "group-status"),
        ("multipath.dm-state", "dm-state"),
        ("multipath.checker-state", "checker-state"),
        ("multipath.online-state", "online-state"),
        ("multipath.path-flags", "path-flags"),
        ("multipath.path-state", "path-state"),
        ("md.version", "md-version"),
        ("md.level", "level"),
        ("md.state", "state"),
        ("md.raid-devices", "raid-devices"),
        ("md.total-devices", "total-devices"),
        ("md.array-devices", "array-devices"),
        ("md.active-devices", "active-devices"),
        ("md.working-devices", "working-devices"),
        ("md.failed-devices", "failed-devices"),
        ("md.spare-devices", "spare-devices"),
        ("md.degraded-devices", "degraded-devices"),
        ("md.name", "md-name"),
        ("md.events", "events"),
        ("md.chunk-size", "chunk"),
        ("md.layout", "layout"),
        ("md.consistency-policy", "consistency"),
        ("md.rebuild-status", "rebuild"),
        ("md.resync-status", "resync"),
        ("md.check-status", "check"),
        ("md.intent-bitmap", "bitmap"),
        ("md.persistence", "persistence"),
        ("md.bitmap", "bitmap-detail"),
        ("md.mdstat-state", "mdstat-state"),
        ("md.mdstat-level", "mdstat-level"),
        ("md.mdstat-blocks", "mdstat-blocks"),
        ("md.mdstat-superblock", "mdstat-superblock"),
        ("md.mdstat-layout", "mdstat-layout"),
        ("md.mdstat-chunk-size", "mdstat-chunk"),
        ("md.mdstat-devices", "mdstat-devices"),
        ("md.mdstat-health", "mdstat-health"),
        ("md.mdstat-progress", "mdstat-progress"),
        ("md.mdstat-progress-percent", "mdstat-progress-percent"),
        ("md.mdstat-progress-blocks", "mdstat-progress-blocks"),
        ("md.mdstat-finish", "mdstat-finish"),
        ("md.mdstat-speed", "mdstat-speed"),
        ("md.mdstat-bitmap", "mdstat-bitmap"),
        ("md.creation-time", "created"),
        ("md.update-time", "updated"),
        ("md.scan-metadata", "scan-metadata"),
        ("md.scan-name", "scan-name"),
        ("md.scan-spares", "scan-spares"),
        ("md.scan-devices", "scan-devices"),
        ("md.member-number", "member-number"),
        ("md.member-major", "member-major"),
        ("md.member-minor", "member-minor"),
        ("md.member-raid-device", "member-raid-device"),
        ("md.member-state", "member-state"),
        ("md.mdstat-member-slot", "mdstat-member-slot"),
        ("md.mdstat-member-flags", "mdstat-member-flags"),
        ("md.uuid", "md-uuid"),
        ("iscsi.target", "target"),
        ("iscsi.portal", "portal"),
        ("iscsi.portal-address", "portal-address"),
        ("iscsi.portal-port", "portal-port"),
        ("iscsi.portal-tpgt", "portal-tpgt"),
        ("iscsi.persistent-portal", "persistent-portal"),
        (
            "iscsi.persistent-portal-address",
            "persistent-portal-address",
        ),
        ("iscsi.persistent-portal-port", "persistent-portal-port"),
        ("iscsi.persistent-portal-tpgt", "persistent-portal-tpgt"),
        ("iscsi.target-portal-group-tag", "tpgt"),
        ("iscsi.connection-state", "connection-state"),
        ("iscsi.session-state", "session-state"),
        ("iscsi.internal-session-state", "internal-session-state"),
        ("iscsi.iface-name", "iface"),
        ("iscsi.iface-transport", "transport"),
        ("iscsi.iface-initiator-name", "initiator"),
        ("iscsi.iface-ip-address", "iface-ip"),
        ("iscsi.iface-netdev", "netdev"),
        ("iscsi.host-number", "host"),
        ("iscsi.host-state", "host-state"),
        ("iscsi.connection-cid", "cid"),
        ("iscsi.connection-detail-state", "connection-detail-state"),
        ("iscsi.connection-local-address", "local-address"),
        ("iscsi.connection-peer-address", "peer-address"),
        ("iscsi.headerdigest", "header-digest"),
        ("iscsi.datadigest", "data-digest"),
        ("iscsi.maxrecvdatasegmentlength", "max-recv-data-segment"),
        ("iscsi.maxxmitdatasegmentlength", "max-xmit-data-segment"),
        ("iscsi.firstburstlength", "first-burst"),
        ("iscsi.maxburstlength", "max-burst"),
        ("iscsi.immediatedata", "immediate-data"),
        ("iscsi.initialr2t", "initial-r2t"),
        ("iscsi.maxoutstandingr2t", "max-outstanding-r2t"),
        ("iscsi.scsi-channel", "scsi-channel"),
        ("iscsi.scsi-id", "scsi-id"),
        ("iscsi.attached-disk", "attached-disk"),
        ("iscsi.attached-disk-state", "attached-disk-state"),
        ("iscsi.node-configured", "configured"),
        ("iscsi.node-portal", "node-portal"),
        ("iscsi.node-portal-address", "node-portal-address"),
        ("iscsi.node-portal-port", "node-portal-port"),
        ("iscsi.node-portal-tpgt", "node-portal-tpgt"),
        ("iscsi.node-persistent-portal", "node-persistent-portal"),
        (
            "iscsi.node-persistent-portal-address",
            "node-persistent-portal-address",
        ),
        (
            "iscsi.node-persistent-portal-port",
            "node-persistent-portal-port",
        ),
        (
            "iscsi.node-persistent-portal-tpgt",
            "node-persistent-portal-tpgt",
        ),
        ("iscsi.node-tpgt", "node-tpgt"),
        ("iscsi.node-iface-name", "node-iface"),
        ("iscsi.node-startup", "startup"),
        ("iscsi.node-leading-login", "leading-login"),
        ("iscsi.node-auth-method", "auth-method"),
        ("iscsi.node-auth-username", "auth-username"),
        ("nfs.source", "source"),
        ("nfs.server", "server"),
        ("nfs.export", "export"),
        ("nfs.export-client", "export-client"),
        ("nfs.exportfs", "exportfs"),
        ("nfs.export-option-rw", "export-rw"),
        ("nfs.export-option-ro", "export-ro"),
        ("nfs.export-option-sync", "export-sync"),
        ("nfs.export-option-async", "export-async"),
        ("nfs.export-option-wdelay", "export-wdelay"),
        ("nfs.export-option-no-wdelay", "export-no-wdelay"),
        ("nfs.export-option-hide", "export-hide"),
        ("nfs.export-option-nohide", "export-nohide"),
        (
            "nfs.export-option-no-subtree-check",
            "export-no-subtree-check",
        ),
        ("nfs.export-option-subtree-check", "export-subtree-check"),
        ("nfs.export-option-sec", "export-sec"),
        ("nfs.export-option-secure", "export-secure"),
        ("nfs.export-option-insecure", "export-insecure"),
        ("nfs.export-option-root-squash", "export-root-squash"),
        ("nfs.export-option-no-root-squash", "export-no-root-squash"),
        ("nfs.export-option-all-squash", "export-all-squash"),
        ("nfs.export-option-no-all-squash", "export-no-all-squash"),
        ("nfs.export-option-fsid", "export-fsid"),
        ("nfs.vers", "vers"),
        ("nfs.proto", "proto"),
        ("nfs.sec", "sec"),
        ("nfs.clientaddr", "clientaddr"),
        ("nfs.addr", "addr"),
        ("nfs.port", "port"),
        ("nfs.mountaddr", "mountaddr"),
        ("nfs.mountvers", "mountvers"),
        ("nfs.mountproto", "mountproto"),
        ("nfs.rsize", "rsize"),
        ("nfs.wsize", "wsize"),
        ("nfs.timeo", "timeo"),
        ("nfs.retrans", "retrans"),
        ("nfs.local-lock", "local-lock"),
        ("nfs.lookupcache", "lookupcache"),
        ("nfs.fsc", "fsc"),
        ("nfs.age", "age"),
        ("nfs.namlen", "namlen"),
        ("nfs.caps", "caps"),
        ("nfs.wtmult", "wtmult"),
        ("nfs.dtsize", "dtsize"),
        ("nfs.bsize", "bsize"),
        ("nfs.flavor", "flavor"),
        ("nfs.pseudoflavor", "pseudoflavor"),
        ("nfs.hard", "hard"),
        ("nfs.soft", "soft"),
        ("nfs.noresvport", "noresvport"),
        ("ext.state", "ext-state"),
        ("ext.magic-number", "ext-magic"),
        ("ext.revision", "ext-revision"),
        ("ext.errors-behavior", "errors"),
        ("ext.fs-error-count", "fs-error-count"),
        ("ext.os-type", "os"),
        ("ext.block-count", "blocks"),
        ("ext.reserved-block-count", "reserved-blocks"),
        ("ext.overhead-clusters", "overhead-clusters"),
        ("ext.free-blocks", "free-blocks"),
        ("ext.first-block", "first-block"),
        ("ext.block-size", "block-size"),
        ("ext.fragment-size", "fragment-size"),
        ("ext.blocks-per-group", "blocks-per-group"),
        ("ext.fragments-per-group", "fragments-per-group"),
        ("ext.inode-count", "inodes"),
        ("ext.free-inodes", "free-inodes"),
        ("ext.inodes-per-group", "inodes-per-group"),
        ("ext.raid-stride", "raid-stride"),
        ("ext.raid-stripe-width", "raid-stripe-width"),
        ("ext.features", "features"),
        ("ext.flags", "flags"),
        ("ext.default-directory-hash", "dir-hash"),
        ("ext.directory-hash-seed", "dir-hash-seed"),
        ("ext.default-mount-options", "default-mount"),
        ("ext.created", "created"),
        ("ext.last-mount-time", "last-mounted"),
        ("ext.last-write-time", "last-written"),
        ("ext.mount-count", "mount-count"),
        ("ext.maximum-mount-count", "max-mount-count"),
        ("ext.last-checked", "last-checked"),
        ("ext.check-interval", "check-interval"),
        ("ext.lifetime-writes", "lifetime-writes"),
        ("ext.reserved-blocks-uid", "reserved-uid"),
        ("ext.reserved-blocks-gid", "reserved-gid"),
        ("ext.first-inode", "first-inode"),
        ("ext.inode-size", "inode-size"),
        ("ext.journal-inode", "journal-inode"),
        ("ext.journal-uuid", "journal-uuid"),
        ("ext.journal-backup", "journal-backup"),
        ("ext.journal-features", "journal-features"),
        ("ext.journal-size", "journal-size"),
        ("ext.first-error-time", "first-error-time"),
        ("ext.first-error-function", "first-error-function"),
        ("ext.first-error-line", "first-error-line"),
        ("ext.first-error-inode", "first-error-inode"),
        ("ext.first-error-block", "first-error-block"),
        ("ext.last-error-time", "last-error-time"),
        ("ext.last-error-function", "last-error-function"),
        ("ext.last-error-line", "last-error-line"),
        ("ext.last-error-inode", "last-error-inode"),
        ("ext.last-error-block", "last-error-block"),
        ("ext.checksum-type", "checksum-type"),
        ("ext.checksum", "checksum"),
        ("exfat.guid", "guid"),
        ("exfat.volume-label", "exfat-label"),
        ("exfat.exfatprogs-version", "exfatprogs"),
        ("exfat.volume-serial", "serial"),
        ("exfat.volume-length-sectors", "sectors"),
        ("exfat.fat-offset-sector-offset", "fat-offset"),
        ("exfat.fat-length-sectors", "fat-length"),
        (
            "exfat.cluster-heap-offset-sector-offset",
            "cluster-heap-offset",
        ),
        ("exfat.cluster-count", "clusters"),
        ("exfat.used-clusters", "used-clusters"),
        ("exfat.free-clusters", "free-clusters"),
        ("exfat.root-cluster-cluster-offset", "root-cluster"),
        ("exfat.bytes-per-sector", "sector-bytes"),
        ("exfat.sectors-per-cluster", "sectors-per-cluster"),
        ("exfat.bytes-per-cluster", "cluster-bytes"),
        ("exfat.sector-size-bits", "sector-bits"),
        ("exfat.sector-per-cluster-bits", "cluster-bits"),
        ("ntfs.device-name", "ntfs-device"),
        ("ntfs.device-state", "ntfs-device-state"),
        ("ntfs.volume-name", "ntfs-name"),
        ("ntfs.volume-state", "ntfs-state"),
        ("ntfs.volume-serial", "ntfs-serial"),
        ("ntfs.volume-flags", "ntfs-flags"),
        ("ntfs.version", "ntfs-version"),
        ("ntfs.sector-size", "ntfs-sector"),
        ("ntfs.cluster-size", "ntfs-cluster"),
        ("ntfs.volume-size-clusters", "ntfs-clusters"),
        ("ntfs.index-block-size", "ntfs-index-block"),
        ("ntfs.mft-record-size", "ntfs-mft-record"),
        ("ntfs.mft-zone-multiplier", "ntfs-mft-zone-multiplier"),
        ("ntfs.mft-zone-start", "ntfs-mft-zone-start"),
        ("ntfs.mft-zone-end", "ntfs-mft-zone-end"),
        ("ntfs.mft-data-position", "ntfs-mft-data-position"),
        ("ntfs.mft-lcn", "ntfs-mft-lcn"),
        ("f2fs.filesystem-uuid", "f2fs-uuid"),
        ("f2fs.filesystem-volume-name", "f2fs-name"),
        ("f2fs.block-size", "f2fs-block-size"),
        ("f2fs.block-count", "f2fs-blocks"),
        ("f2fs.user-block-count", "f2fs-user-blocks"),
        ("f2fs.valid-block-count", "f2fs-valid-blocks"),
        ("f2fs.total-valid-block-count", "f2fs-total-valid-blocks"),
        ("f2fs.valid-node-count", "f2fs-valid-nodes"),
        ("f2fs.valid-inode-count", "f2fs-valid-inodes"),
        ("f2fs.segment-count", "f2fs-segments"),
        ("f2fs.segment-count-main", "f2fs-main-segments"),
        ("f2fs.segment-count-ckpt", "f2fs-ckpt-segments"),
        ("f2fs.segment-count-sit", "f2fs-sit-segments"),
        ("f2fs.segment-count-nat", "f2fs-nat-segments"),
        ("f2fs.segment-count-ssa", "f2fs-ssa-segments"),
        ("f2fs.overprov-segment-count", "f2fs-overprov"),
        ("f2fs.section-count", "f2fs-sections"),
        ("f2fs.segs-per-sec", "f2fs-segs-per-sec"),
        ("f2fs.secs-per-zone", "f2fs-secs-per-zone"),
        ("f2fs.log-sectorsize", "f2fs-log-sector"),
        ("f2fs.log-sectors-per-block", "f2fs-log-sectors-block"),
        ("f2fs.log-blocksize", "f2fs-log-block"),
        ("f2fs.log-blocks-per-seg", "f2fs-log-blocks-seg"),
        ("f2fs.cp-payload", "f2fs-cp-payload"),
        ("f2fs.version", "f2fs-version"),
        ("f2fs.init-version", "f2fs-init-version"),
        ("f2fs.extension-count", "f2fs-extensions"),
        ("f2fs.hot-ext-count", "f2fs-hot-extensions"),
        ("scsi.address", "scsi-address"),
        ("scsi.host", "scsi-host"),
        ("scsi.channel", "scsi-channel"),
        ("scsi.target", "scsi-target"),
        ("scsi.lun", "scsi-lun"),
        ("scsi.peripheral-type", "scsi-type"),
        ("scsi.vendor", "scsi-vendor"),
        ("scsi.model", "scsi-model"),
        ("scsi.revision", "scsi-revision"),
        ("scsi.block-device", "scsi-block"),
        ("scsi.generic-device", "scsi-generic"),
        ("scsi.size", "scsi-size"),
        ("scsi.transport", "scsi-transport"),
        ("scsi.unit-name", "scsi-unit"),
        ("scsi.by-id", "scsi-by-id"),
        ("scsi.wwn", "scsi-wwn"),
        ("scsi.state", "scsi-state"),
        ("scsi.queue-depth", "scsi-queue-depth"),
        ("scsi.queue-type", "scsi-queue-type"),
        ("scsi.scsi-level", "scsi-level"),
        ("scsi.timeout", "scsi-timeout"),
        ("bcachefs.external-uuid", "bcachefs-uuid"),
        ("bcachefs.internal-uuid", "bcachefs-internal"),
        ("bcachefs.magic-number", "bcachefs-magic"),
        ("bcachefs.device", "bcachefs-super-device"),
        ("bcachefs.member-device", "bcachefs-member"),
        ("bcachefs.mount-target", "bcachefs-mount"),
        ("bcachefs.device-index", "bcachefs-device"),
        ("bcachefs.version", "bcachefs-version"),
        (
            "bcachefs.version-upgrade-complete",
            "bcachefs-upgrade-complete",
        ),
        ("bcachefs.online-reserved", "bcachefs-reserved"),
        ("bcachefs.device-count", "bcachefs-devices"),
        ("bcachefs.data-sb", "bcachefs-sb"),
        ("bcachefs.data-journal", "bcachefs-journal"),
        ("bcachefs.data-btree", "bcachefs-btree"),
        ("bcachefs.data-user", "bcachefs-user"),
        ("bcachefs.data-cached", "bcachefs-cached"),
        ("bcachefs.data-parity", "bcachefs-parity"),
        ("bcachefs.device-label", "bcachefs-label"),
        ("bcachefs.device-state", "bcachefs-state"),
        ("bcachefs.device-free", "bcachefs-device-free"),
        ("bcachefs.device-capacity", "bcachefs-device-capacity"),
        ("bcachefs.device-data-sb", "bcachefs-device-sb"),
        ("bcachefs.device-data-journal", "bcachefs-device-journal"),
        ("bcachefs.device-data-btree", "bcachefs-device-btree"),
        ("bcachefs.device-data-user", "bcachefs-device-user"),
        ("bcachefs.device-data-cached", "bcachefs-device-cached"),
        ("bcache.role", "role"),
        ("bcache.kind", "kind"),
        ("bcache.backing-device", "backing-device"),
        ("bcache.set-uuid", "set-uuid"),
        ("bcache.set-average-key-size", "set-average-key-size"),
        ("bcache.set-btree-cache-size", "set-btree-cache-size"),
        (
            "bcache.set-cache-available-percent",
            "set-available-percent",
        ),
        ("bcache.set-congested", "set-congested"),
        (
            "bcache.set-congested-read-threshold-us",
            "set-congested-read-us",
        ),
        (
            "bcache.set-congested-write-threshold-us",
            "set-congested-write-us",
        ),
        ("bcache.set-io-error-halflife", "set-io-error-halflife"),
        ("bcache.set-io-error-limit", "set-io-error-limit"),
        ("bcache.set-journal-delay-ms", "set-journal-delay-ms"),
        ("bcache.set-root-usage-percent", "set-root-usage-percent"),
        ("bcache.label", "label"),
        ("bcache.state", "state"),
        ("bcache.running", "running"),
        ("bcache.cache-available-percent", "available-percent"),
        ("bcache.cache-mode", "cache-mode"),
        ("bcache.cache-replacement-policy", "replacement"),
        ("bcache.congested-read-threshold-us", "congested-read-us"),
        ("bcache.congested-write-threshold-us", "congested-write-us"),
        ("bcache.discard", "discard"),
        ("bcache.dirty-data", "dirty"),
        ("bcache.io-errors", "io-errors"),
        ("bcache.metadata-written", "metadata-written"),
        ("bcache.priority-stats", "priority-stats"),
        ("bcache.readahead", "readahead"),
        ("bcache.sequential-cutoff", "sequential-cutoff"),
        ("bcache.written", "written"),
        ("bcache.writeback-delay", "writeback-delay"),
        ("bcache.writeback-metadata", "writeback-metadata"),
        ("bcache.writeback-percent", "writeback-percent"),
        ("bcache.writeback-rate", "writeback-rate"),
        ("bcache.writeback-rate-debug", "writeback-rate-debug"),
        ("bcache.writeback-rate-d-term", "writeback-rate-d-term"),
        (
            "bcache.writeback-rate-i-term-inverse",
            "writeback-rate-i-inverse",
        ),
        ("bcache.writeback-rate-minimum", "writeback-rate-min"),
        (
            "bcache.writeback-rate-p-term-inverse",
            "writeback-rate-p-inverse",
        ),
        (
            "bcache.writeback-rate-update-seconds",
            "writeback-rate-update",
        ),
        ("bcache.writeback-running", "writeback-running"),
        ("zfs.health", "health"),
        ("zfs.pool-capacity", "pool-capacity"),
        ("zfs.pool-dedupratio", "pool-dedupratio"),
        ("zfs.pool-fragmentation", "pool-fragmentation"),
        ("zfs.pool-altroot", "pool-altroot"),
        ("zfs.pool-ashift", "pool-ashift"),
        ("zfs.pool-autotrim", "pool-autotrim"),
        ("zfs.pool-autoexpand", "pool-autoexpand"),
        ("zfs.pool-autoreplace", "pool-autoreplace"),
        ("zfs.pool-bootfs", "pool-bootfs"),
        ("zfs.pool-cachefile", "pool-cachefile"),
        ("zfs.pool-comment", "pool-comment"),
        ("zfs.pool-delegation", "pool-delegation"),
        ("zfs.pool-failmode", "pool-failmode"),
        ("zfs.pool-listsnapshots", "pool-listsnapshots"),
        ("zfs.pool-multihost", "pool-multihost"),
        ("zfs.state", "state"),
        ("zfs.status", "status"),
        ("zfs.action", "action"),
        ("zfs.scan", "scan"),
        ("zfs.errors", "errors"),
        ("zfs.pool-read-errors", "pool-read-errors"),
        ("zfs.pool-write-errors", "pool-write-errors"),
        ("zfs.pool-checksum-errors", "pool-checksum-errors"),
        ("zfs.vdev-role", "vdev-role"),
        ("zfs.vdev-state", "vdev-state"),
        ("zfs.read-errors", "read-errors"),
        ("zfs.write-errors", "write-errors"),
        ("zfs.checksum-errors", "checksum-errors"),
        ("zfs.origin", "origin"),
        ("zfs.userrefs", "userrefs"),
        ("zfs.holds", "holds"),
        ("zfs.compression", "compression"),
        ("zfs.quota", "quota"),
        ("zfs.reservation", "reservation"),
        ("zfs.encryption", "encryption"),
        ("zfs.keystatus", "keystatus"),
        ("zfs.volsize", "volsize"),
        ("zfs.recordsize", "recordsize"),
        ("zfs.dedup", "dedup"),
        ("zfs.checksum", "checksum"),
        ("zfs.copies", "copies"),
        ("zfs.sync", "sync"),
        ("zfs.primarycache", "primarycache"),
        ("zfs.secondarycache", "secondarycache"),
        ("zfs.atime", "atime"),
        ("zfs.relatime", "relatime"),
        ("zfs.snapdir", "snapdir"),
        ("zfs.acltype", "acltype"),
        ("zfs.xattr", "xattr"),
        ("xfs.meta-data.meta-data", "xfs-source"),
        ("xfs.meta-data.isize", "xfs-isize"),
        ("xfs.meta-data.agcount", "xfs-agcount"),
        ("xfs.meta-data.agsize", "xfs-agsize"),
        ("xfs.meta-data.sectsz", "xfs-sectsz"),
        ("xfs.meta-data.attr", "xfs-attr"),
        ("xfs.meta-data.projid32bit", "xfs-projid32bit"),
        ("xfs.meta-data.crc", "xfs-crc"),
        ("xfs.meta-data.finobt", "xfs-finobt"),
        ("xfs.meta-data.sparse", "xfs-sparse"),
        ("xfs.meta-data.rmapbt", "xfs-rmapbt"),
        ("xfs.data.blocks", "xfs-blocks"),
        ("xfs.data.bsize", "xfs-bsize"),
        ("xfs.data.imaxpct", "xfs-imaxpct"),
        ("xfs.data.sunit", "xfs-sunit"),
        ("xfs.data.swidth", "xfs-swidth"),
        ("xfs.meta-data.reflink", "reflink"),
        ("xfs.meta-data.bigtime", "bigtime"),
        ("xfs.meta-data.inobtcount", "xfs-inobtcount"),
        ("xfs.meta-data.nrext64", "xfs-nrext64"),
        ("xfs.naming.version", "xfs-naming-version"),
        ("xfs.naming.bsize", "xfs-naming-bsize"),
        ("xfs.naming.ascii-ci", "xfs-ascii-ci"),
        ("xfs.naming.ftype", "xfs-ftype"),
        ("xfs.log.type", "xfs-log-type"),
        ("xfs.log.bsize", "xfs-log-bsize"),
        ("xfs.log.blocks", "log-blocks"),
        ("xfs.log.version", "xfs-log-version"),
        ("xfs.log.sectsz", "xfs-log-sectsz"),
        ("xfs.log.sunit", "xfs-log-sunit"),
        ("xfs.log.lazy-count", "xfs-log-lazy-count"),
        ("xfs.realtime.type", "xfs-realtime-type"),
        ("xfs.realtime.extsz", "xfs-realtime-extsz"),
        ("xfs.realtime.blocks", "xfs-realtime-blocks"),
        ("xfs.realtime.rtextents", "xfs-realtime-rtextents"),
    ];

    let details = DETAIL_KEYS
        .iter()
        .filter_map(|(key, label)| {
            property_value(node, key).map(|value| format!("{label}={value}"))
        })
        .collect::<Vec<_>>();

    if details.is_empty() {
        "-".to_string()
    } else {
        details.join(" ")
    }
}
