''
  and .spec.vdoVolumes.archiveLifecycle.operation == "grow"
  and .spec.vdoVolumes.archiveLifecycle.desiredSize == "4TiB"
  and .spec.vdoVolumes.archiveLifecycle.physicalSize == "6TiB"
  and .spec.vdoVolumes.archiveLifecycle.properties.writePolicy == "sync"
  and .spec.vdoVolumes.archiveLifecycle.properties.compression == "enabled"
  and .spec.vdoVolumes.archiveLifecycle.properties.deduplication == "disabled"
  and .spec.vdoVolumes.warmArchive.target == "warm-archive"
  and .spec.vdoVolumes.warmArchive.operation == "start"
  and .spec.vdoVolumes.coldArchive.target == "cold-archive"
  and .spec.vdoVolumes.coldArchive.operation == "stop"
  and .spec.vdoVolumes.refreshArchive.target == "refresh-archive"
  and .spec.vdoVolumes.refreshArchive.operation == "rescan"
  and .spec.physicalVolumes.nvmePvGrow.operation == "grow"
  and .spec.physicalVolumes.nvmePvGrow.path == "/dev/disk/by-id/nvme-pv-grow"
  and .spec.physicalVolumes."/dev/disk/by-id/nvme-pv-refresh".operation == "rescan"
  and .spec.luksKeyslots."cryptroot:1".operation == "add-key"
  and .spec.luksKeyslots."cryptroot:1".device == "/dev/disk/by-id/root-luks"
  and .spec.luksKeyslots."cryptroot:1".keySlot == "1"
  and .spec.luksKeyslots."cryptroot:1".newKeyFile == "/run/keys/root-new"
  and .spec.luksKeyslots."cryptroot:2".operation == "remove-key"
  and .spec.luksKeyslots."cryptroot:2".device == "/dev/disk/by-id/root-luks"
  and .spec.luksKeyslots."cryptroot:2".keySlot == "2"
  and .spec.luksKeyslots."cryptroot:3"."key-slot" == "3"
  and .spec.luksKeyslots."cryptroot:3"."new-key-file" == "/run/keys/root-new-alias"
  and .spec.luksKeyslots."cryptroot:4".slot == "4"
  and .spec.luksTokens."cryptroot:0".operation == "import-token"
  and .spec.luksTokens."cryptroot:0".device == "/dev/disk/by-id/root-luks"
  and .spec.luksTokens."cryptroot:0".tokenId == "0"
  and .spec.luksTokens."cryptroot:0".tokenFile == "/run/keys/root-token.json"
  and .spec.luksTokens."cryptroot:1".operation == "remove-token"
  and .spec.luksTokens."cryptroot:1".device == "/dev/disk/by-id/root-luks"
  and .spec.luksTokens."cryptroot:1".tokenId == "1"
  and .spec.luksTokens."cryptroot:2".token == "2"
  and .spec.luksTokens."cryptroot:2"."token-file" == "/run/keys/root-token-alias.json"
  and .spec.luksTokens."cryptroot:3"."token-id" == "3"
  and .spec.zvols."tank/vm/root".operation == "grow"
  and .spec.zvols."tank/vm/root".desiredSize == "80GiB"
  and .spec.zvols."tank/vm/inventory".operation == "rescan"
  and .spec.thinPools.primaryPool.operation == "grow"
  and .spec.thinPools.primaryPool.path == "vg0/thinpool"
  and .spec.thinPools.primaryPool.desiredSize == "500GiB"
  and .spec.thinPools."vg0/newthin".operation == "create"
  and .spec.thinPools."vg0/newthin".desiredSize == "100GiB"
  and .spec.thinPools."vg0/reporting".operation == "rescan"
  and .spec.lvmSnapshots."vg0/root-snap".operation == "snapshot"
  and .spec.lvmSnapshots."vg0/root-snap".target == "vg0/root"
  and .spec.lvmSnapshots."vg0/root-snap".desiredSize == "20GiB"
  and .spec.lvmSnapshots."vg0/root-inspect".operation == "rescan"
  and .spec.lvmCaches."vg0/root".operation == "create"
  and .spec.lvmCaches."vg0/root".device == "vg0/root-cache"
  and .spec.lvmCaches."vg0/root".properties."lvm.cache-mode" == "writethrough"
  and .spec.lvmCaches."vg0/archive".operation == "rescan"
  and .spec.volumes."vg0/archive".operation == "deactivate"
  and .spec.loopDevices.rootImage.operation == "create"
  and .spec.loopDevices.rootImage.path == "/dev/loop7"
  and .spec.loopDevices.rootImage.device == "/var/lib/images/root.img"
  and .spec.loopDevices."/dev/loop10".operation == "rescan"
  and .spec.backingFiles."/var/lib/images/new.img".operation == "create"
  and .spec.backingFiles."/var/lib/images/new.img".desiredSize == "8GiB"
  and .spec.backingFiles."/var/lib/images/root.img".operation == "grow"
  and .spec.backingFiles."/var/lib/images/root.img".desiredSize == "16GiB"
  and .spec.backingFiles.inventoryImage.operation == "rescan"
  and .spec.backingFiles.inventoryImage.path == "/var/lib/images/inventory.img"
  and .spec.dmMaps.cryptroot.operation == "rescan"
  and .spec.dmMaps.cryptroot.target == "/dev/mapper/cryptroot"
  and .spec.dmMaps.cryptswap.operation == "rename"
  and .spec.dmMaps.cryptswap.target == "/dev/mapper/cryptswap"
  and .spec.dmMaps.cryptswap.renameTo == "cryptswap-retired"
  and .spec.dmMaps.oldmap.operation == "destroy"
  and .spec.dmMaps.oldmap.target == "/dev/mapper/oldmap"
  and .spec.mdRaids.root.target == "/dev/md/root"
  and .spec.mdRaids.root.raidLevel == "1"
  and (.spec.mdRaids.root.devices | index("/dev/disk/by-id/nvme-md-a") != null)
  and (.spec.mdRaids.root.devices | index("/dev/disk/by-id/nvme-md-b") != null)
  and (.spec.mdRaids.root.addDevices | index("/dev/disk/by-id/nvme-md-spare") != null)
  and .spec.mdRaids.root.replaceDevices."/dev/disk/by-id/nvme-md-aging" == "/dev/disk/by-id/nvme-md-replacement"
  and .spec.mdRaids.existing.operation == "assemble"
  and .spec.mdRaids.existing.target == "/dev/md/existing"
  and (.spec.mdRaids.existing.devices | index("/dev/disk/by-id/existing-md-a") != null)
  and .spec.mdRaids.oldroot.operation == "stop"
  and .spec.mdRaids.oldroot.target == "/dev/md/oldroot"
  and .spec.mdRaids.inventory.operation == "rescan"
  and .spec.multipathMaps.mpatha.target == "mpatha"
  and (.spec.multipathMaps.mpatha.addDevices | index("/dev/sdb") != null)
  and .spec.multipathMaps.mpatha.replaceDevices."/dev/sdc" == "/dev/sdd"
  and .spec.multipathMaps.mpathb.operation == "rescan"
  and .spec.multipathMaps.mpathb.target == "mpathb"
  and .spec.multipathMaps.mpathOld.operation == "destroy"
  and .spec.multipathMaps.mpathOld.target == "mpath-old"
  and .spec.caches."tank/l2arc0".cacheSetUuid == "11111111-2222-3333-4444-555555555555"
  and (.spec.caches."/dev/bcache0".addDevices | index("cache-set-uuid") != null)

''
