''
  and .spec.iscsi.initiatorName == "iqn.2026-06.example:host"
  and (.spec.iscsi | has("discoverPortal") | not)
  and (.spec.iscsi.boot | has("discoverPortal") | not)
  and .spec.iscsi.boot.target == "iqn.2026-06.example:storage.root"
  and .spec.iscsi.sessions."iqn.2026-06.example:storage.root".operation == "grow"
  and .spec.iscsi.sessions."iqn.2026-06.example:storage.root".desiredSize == "2TiB"
  and .spec.iscsi.sessions."iqn.2026-06.example:storage.alias".targetSize == "3TiB"
  and .spec.iscsi.sessions."iqn.2026-06.example:storage.login".operation == "login"
  and .spec.iscsi.sessions."iqn.2026-06.example:storage.logout".operation == "logout"
  and .spec.iscsi.sessions."iqn.2026-06.example:storage.rescan".operation == "rescan"
  and .spec.iscsiSessions."iqn.2026-06.example:storage.root".portal == "192.0.2.10:3260"
  and .spec.iscsiSessions."iqn.2026-06.example:storage.root".operation == "grow"
  and .spec.iscsiSessions."iqn.2026-06.example:storage.root".desiredSize == "2TiB"
  and .spec.iscsiSessions."iqn.2026-06.example:storage.alias".targetSize == "3TiB"
  and .spec.iscsiSessions."iqn.2026-06.example:storage.login".operation == "login"
  and .spec.iscsiSessions."iqn.2026-06.example:storage.login".portal == "192.0.2.10:3260"
  and .spec.iscsiSessions."iqn.2026-06.example:storage.logout".operation == "logout"
  and .spec.iscsiSessions."iqn.2026-06.example:storage.logout".portal == "192.0.2.11:3260"
  and .spec.iscsiSessions."iqn.2026-06.example:storage.rescan".operation == "rescan"
  and .spec.iscsiSessions."iqn.2026-06.example:storage.rescan".portal == "192.0.2.10:3260"
  and .spec.luns."iqn.2026-06.example:storage/root:0".lun == 0
  and .spec.luns."iqn.2026-06.example:storage/root:0".device == "/dev/disk/by-path/ip-192.0.2.10:3260-iscsi-iqn.2026-06.example:storage-lun-0"
  and (.spec.luns."iqn.2026-06.example:storage/root:0".devices | index("/dev/disk/by-path/ip-192.0.2.11:3260-iscsi-iqn.2026-06.example:storage-lun-0") != null)
  and .spec.luns."iqn.2026-06.example:storage/new:2".operation == "attach"
  and .spec.luns."iqn.2026-06.example:storage/new:2".device == "/dev/disk/by-path/ip-192.0.2.10:3260-iscsi-iqn.2026-06.example:storage-lun-2"
  and .spec.luns."iqn.2026-06.example:storage/old:3".operation == "detach"
  and (.spec.luns."iqn.2026-06.example:storage/old:3".devices | index("/dev/disk/by-path/ip-192.0.2.11:3260-iscsi-iqn.2026-06.example:storage-lun-3") != null)
  and .spec.luns."iqn.2026-06.example:storage/rescan:4".operation == "rescan"
  and (.spec.luns."iqn.2026-06.example:storage/rescan:4".paths | index("/dev/disk/by-path/ip-192.0.2.10:3260-iscsi-iqn.2026-06.example:storage-lun-4") != null)
  and .spec.nvmeNamespaces.rootNamespace.operation == "create"
  and .spec.nvmeNamespaces.rootNamespace.path == "/dev/nvme0"
  and .spec.nvmeNamespaces.rootNamespace.desiredSize == "100G"
  and .spec.nvmeNamespaces.rootNamespace.namespaceId == "4"
  and .spec.nvmeNamespaces.rootNamespace.controllers == "0x1"
  and .spec.nvmeNamespaces."/dev/nvme1".operation == "rescan"
  and .spec.nvmeNamespaces."/dev/nvme2".nsid == "7"
  and .spec.nvmeNamespaces."/dev/nvme2".controllerId == "0x2"
  and .spec.nvmeNamespaces."/dev/nvme3".namespaceId == "8"
  and .spec.nvmeNamespaces."/dev/nvme3".controller == "0x3"
  and .spec.exports.share.operation == "export"
  and .spec.exports.share.path == "/srv/share"
  and .spec.exports.share.client == "192.0.2.0/24"
  and .spec.exports.share.options == "rw,sync,no_subtree_check"
  and .spec.exports."/srv/inventory".operation == "rescan"
  and .spec.exports."/srv/old-share".operation == "unexport"
  and .spec.exports."/srv/old-share".client == "192.0.2.55"
  and .spec.partitions.root.operation == "grow"
  and .spec.partitions.root.device == "/dev/disk/by-id/nvme-root"
  and .spec.partitions.root.number == "2"
  and .spec.partitions.root.endOffset == "100%"
  and .spec.partitions.dataTable.operation == "rescan"
  and .spec.partitions.dataTable.device == "/dev/disk/by-id/nvme-data"
  and .spec.btrfsSubvolumes."/mnt/persist/@home".operation == "create"
  and .spec.btrfsSubvolumes."/mnt/persist/@home".path == "/mnt/persist/@home"
  and .spec.btrfsSubvolumes."/mnt/persist/@inventory".operation == "rescan"
  and .spec.btrfsSubvolumes."/mnt/persist/@inventory".path == "/mnt/persist/@inventory"
  and .spec.btrfsSubvolumes."/mnt/persist/@old-name".operation == "rename"
  and .spec.btrfsSubvolumes."/mnt/persist/@old-name".renameTo == "/mnt/persist/@new-name"
  and .spec.btrfsQgroups."0/257".target == "/mnt/persist"
  and .spec.btrfsQgroups."0/257".properties.limit == "25GiB"
  and .spec.btrfsQgroups."0/258".operation == "rescan"
  and .spec.btrfsQgroups."0/258".target == "/mnt/persist"
  and .spec.volumes.scratch.operation == "create"
  and .spec.volumes.scratch.target == "vg0/scratch"
  and .spec.volumes.scratch.desiredSize == "10GiB"
  and .spec.volumes."vg0/size-alias".size == "12GiB"
  and .spec.volumes."vg0/reporting".operation == "rescan"
  and .spec.datasets."tank/home".operation == "create"
  and .spec.datasets."tank/inventory".operation == "rescan"
  and .spec.vdoVolumes.archiveLifecycle.target == "archive"

''
