''
      and .spec.caches."/dev/bcache0".cacheSetUuid == "cache-set-uuid"
      and .spec.caches."/dev/bcache0".operation == "rescan"
      and .spec.caches."/dev/bcache0".properties."bcache.cache-mode" == "writethrough"
      and .spec.caches."/dev/bcache0".properties."bcache.set-journal-delay-ms" == "100"
      and .spec.pools.vault.operation == "import"
      and .spec.pools.vault.readOnly == true
      and .spec.pools.archiveImport.readonly == true
      and .spec.pools.moveme.operation == "export"
      and .spec.volumeGroups.importvg.operation == "import"
      and .spec.volumeGroups.exportvg.operation == "export"
      and .spec.volumeGroups.activevg.operation == "activate"
      and .spec.volumeGroups.refreshvg.operation == "rescan"
      and .spec.volumeGroups.actionvg.action == "rescan"
      and .spec.datasets."tank/home-review".operation == "promote"
      and .spec.datasets."tank/legacy-alias".renameTarget == "tank/legacy-alias-staged"
      and .spec.datasets."tank/legacy-short".newName == "tank/legacy-short-staged"
      and .spec.snapshots."tank/home@before-upgrade".target == "tank/home"
      and .spec.snapshots."tank/home@before-upgrade".hold == "disk-nix-retain"
      and .spec.snapshots."tank/home@before-upgrade".rollback == true
  and .spec.snapshots."tank/home@before-upgrade".cloneTo == "tank/home-review"
  and .spec.snapshots."tank/home@before-upgrade".renameTo == "tank/home@before-upgrade-retained"
  and .spec.snapshots."tank/home@before-upgrade".recursiveRollback == true
  and .spec.snapshots."tank/home@clone-only".operation == "clone"
  and .spec.snapshots."tank/home@clone-only".cloneTo == "tank/home-clone"
  and .spec.snapshots."tank/home@action-rescan".action == "rescan"
  and .spec.snapshots.aliases.operation == "clone"
  and .spec.snapshots.aliases."snapshot-path" == "tank/home@alias-source"
  and .spec.snapshots.aliases.cloneTarget == "tank/home-alias-clone"
  and .spec.snapshots.aliases.clone == "tank/home-short-clone"
  and .spec.snapshots.aliases.renameTarget == "tank/home@alias-retained"
  and .spec.snapshots.aliases.newName == "tank/home@alias-new"
  and .spec.snapshots.aliases.recursive == true
  and .spec.snapshots.aliases."zfs.rollbackRecursive" == true
  and .spec.snapshots.aliases.readonly == true
  and .spec.datasets."tank/legacy".renameTo == "tank/legacy-staged"
      and .spec.snapshots."tank/home@old".releaseHold == "old-retention"
      and .spec.snapshots."/mnt/persist/@home-before-upgrade".target == "/mnt/persist/@home"
      and .spec.snapshots."/mnt/persist/@home-before-upgrade".readOnly == true
      and .spec.snapshots."/mnt/persist/@home-before-clone".target == "/mnt/persist/@home"
      and .spec.snapshots."/mnt/persist/@home-before-clone".cloneTo == "/mnt/persist/@home-review"
      and .spec.snapshots."/mnt/persist/@home-before-clone".readOnly == true
      and .spec.snapshots."tank/home@inventory".operation == "rescan"
      and .spec.snapshots."/mnt/persist/@home-inventory".operation == "rescan"
      and .spec.snapshots."/mnt/persist/@home-inventory".readOnly == true
      and .spec.snapshots."home-before-friendly".operation == "rescan"
      and .spec.snapshots."home-before-friendly".target == "/mnt/persist/@home"
      and .spec.snapshots."home-before-friendly".snapshotPath == "/mnt/persist/@home-before-friendly"
      and .apply.mode == "activation"
      and .apply.allowGrow == true
      and .apply.allowOffline == false
      and .apply.probeCurrent == true
      and .apply.allowDeviceReplacement == true
      and .apply.allowRebalance == true
      and .apply.allowPotentialDataLoss == false
      and .apply.requireBackup == false
      and .apply.backupVerified == false
      and .apply.requireConfirmation == false
      and .apply.confirmation == false
      and .apply.requireConfirmationFile == "/run/disk-nix/confirm"
      and .apply.failOnBlocked == false
      and .apply.scriptOut == "/run/disk-nix/apply.sh"
      and .apply.reportOut == "/run/disk-nix/apply-report.json"
      and .apply.receiptOut == "/run/disk-nix/apply-receipt.json"

''
