{
  pkgs,
  nixosModuleTest,
  zramTuningOnlyModuleTest,
  ...
}:

pkgs.runCommand "disk-nix-nixos-module-handoff-zram-check" { nativeBuildInputs = [ pkgs.jq ]; } ''
      handoffNix=${nixosModuleTest.config.environment.etc."disk-nix/declarative-handoff.nix".source}
      grep -F -- 'Generated by services.disk-nix' "$handoffNix"
      grep -F -- 'This file is not imported by default' "$handoffNix"
      grep -F -- 'fileSystems = {' "$handoffNix"
      grep -F -- '"/mnt/local-mount" = {' "$handoffNix"
      grep -F -- 'swapDevices = [' "$handoffNix"
      grep -F -- 'zramSwap = {' "$handoffNix"
      grep -F -- 'luks = {' "$handoffNix"
      grep -F -- 'devices = {' "$handoffNix"
      grep -F -- 'supportedFilesystems = [' "$handoffNix"
      grep -F -- 'openiscsi = {' "$handoffNix"
      grep -F -- 'extraPools = [' "$handoffNix"
      handoffPatch=${
        nixosModuleTest.config.environment.etc."disk-nix/declarative-handoff-import.patch".source
      }
      grep -F -- 'Generated by services.disk-nix' "$handoffPatch"
      grep -F -- 'This patch is intentionally not applied by default' "$handoffPatch"
      grep -F -- 'imports = [' "$handoffPatch"
      grep -F -- '/etc/disk-nix/declarative-handoff.nix' "$handoffPatch"
      printf '%s\n' ${pkgs.lib.escapeShellArg nixosModuleTest.config.services.nfs.server.exports} > nfs-exports
      grep -- '/srv/share 192.0.2.0/24(rw,sync,no_subtree_check)' nfs-exports
      ! grep -- '/srv/old-share' nfs-exports
      tuningOnlySpec=${zramTuningOnlyModuleTest.config.environment.etc."disk-nix/spec.json".source}
      jq -e '
        .spec.zram.swapDevices == 3
        and .spec.zram.memoryPercent == 35
        and .spec.zram.priority == 15
        and .spec.zram.algorithm == "lz4"
        and .spec.zram.preserveData == false
        and ((.spec.zram.enable // false) == false)
      ' "$tuningOnlySpec"
      tuningOnlyNative=${
        pkgs.lib.escapeShellArg (
          builtins.toJSON {
            zram = zramTuningOnlyModuleTest.config.zramSwap.enable;
          }
        )
      }
      printf '%s\n' "$tuningOnlyNative" > tuning-only-native-storage
      jq -e '.zram == false' tuning-only-native-storage
  touch "$out"
''
