{
  pkgs,
  nixosModuleTest,
  ...
}:

pkgs.runCommand "disk-nix-nixos-module-spec-json-check" { nativeBuildInputs = [ pkgs.jq ]; } ''
      spec=${nixosModuleTest.config.environment.etc."disk-nix/spec.json".source}
      jq -e '
        .version == 1
        and .spec.filesystems.root.device == "/dev/disk/by-label/nixos-root"
        and .spec.filesystems.root.resizePolicy == "grow-only"
        and .spec.filesystems.root.desiredSize == "100%"
        and .spec.filesystems.data.device == "/dev/disk/by-label/data"
        and .spec.filesystems.data.fsType == "btrfs"
        and .spec.filesystems.data.operation == "rebalance"
        and (.spec.filesystems.data.addDevices | index("/dev/disk/by-id/nvme-btrfs-new") != null)
        and (.spec.filesystems.data.removeDevices | index("/dev/disk/by-id/nvme-btrfs-old") != null)
        and .spec.filesystems.data.replaceDevices."/dev/disk/by-id/nvme-btrfs-aging" == "/dev/disk/by-id/nvme-btrfs-replacement"
        and .spec.filesystems.data.properties.label == "bulk-data"
        and .spec.filesystems.data.properties."btrfs.balance.data" == "usage=50"
        and .spec.filesystems.data.metadata.pool == "tank"
        and .spec.filesystems.data.metadata.role == "bulk-data"
        and .spec.filesystems.scratch.operation == "check"
        and .spec.filesystems.scratch.device == "/dev/disk/by-label/scratch"
        and .spec.filesystems.scrub.operation == "scrub"
        and .spec.filesystems.scrub.device == "/dev/disk/by-label/scrub"
        and .spec.filesystems.scrub.mountpoint == "/scrub"
        and .spec.filesystems.trim.operation == "trim"
        and .spec.filesystems.trim.device == "/dev/disk/by-label/trim"
        and .spec.filesystems.remount.operation == "remount"
        and .spec.filesystems.remount.mountpoint == "/remount"
        and (.spec.filesystems.remount.options | index("discard=async") != null)
        and .spec.filesystems.localMount.operation == "mount"
        and .spec.filesystems.localMount.device == "/dev/disk/by-label/local-mount"
        and .spec.filesystems.localMount.mountpoint == "/mnt/local-mount"
        and (.spec.filesystems.localMount.options | index("noatime") != null)
        and .spec.filesystems.localUnmount.operation == "unmount"
        and .spec.filesystems.localUnmount.device == "/dev/disk/by-label/local-unmount"
        and .spec.filesystems.localUnmount.mountpoint == "/mnt/local-unmount"
        and .spec.filesystems.localRescan.operation == "rescan"
        and .spec.filesystems.localRescan.device == "/dev/disk/by-label/local-rescan"
        and .spec.filesystems.localRescan.mountpoint == "/mnt/local-rescan"
        and .spec.filesystems.actionRescan.action == "rescan"
        and .spec.filesystems.actionUnmount.action == "unmount"
        and .spec.filesystems.destroyed.destroy == true
        and .spec.filesystems.destroyed.device == "/dev/disk/by-label/destroyed"
        and .spec.filesystems.targetSizeAlias.operation == "rescan"
        and .spec.filesystems.targetSizeAlias.targetSize == "200GiB"
        and .spec.filesystems.sizeAlias.operation == "rescan"
        and .spec.filesystems.sizeAlias.size == "150GiB"
        and .spec.filesystems.runTmpfs.device == "tmpfs"
        and .spec.filesystems.runTmpfs.fsType == "tmpfs"
        and .spec.filesystems.runTmpfs.mountpoint == "/run/disk-nix-tmp"
        and (.spec.filesystems.runTmpfs.options | index("size=64M") != null)
        and .spec.filesystems.bindCache.device == "/var/cache/disk-nix"
        and .spec.filesystems.bindCache.fsType == "none"
        and .spec.filesystems.bindCache.mountpoint == "/srv/disk-nix-cache"
        and (.spec.filesystems.bindCache.options | index("bind") != null)
        and .spec.filesystems.overlayScratch.device == "overlay"
        and .spec.filesystems.overlayScratch.fsType == "overlay"
        and .spec.filesystems.overlayScratch.mountpoint == "/srv/disk-nix-overlay"
        and (.spec.filesystems.overlayScratch.options | index("lowerdir=/nix/store") != null)
        and (.spec.filesystems.overlayScratch.options | index("upperdir=/var/lib/disk-nix/overlay/upper") != null)
        and (.spec.filesystems.overlayScratch.options | index("workdir=/var/lib/disk-nix/overlay/work") != null)
        and .spec.swaps.primary.device == "/dev/disk/by-label/swap"
        and .spec.swaps.primary.operation == "format"
        and .spec.swaps.primary.desiredSize == "8GiB"
        and .spec.swaps.primary.preserveData == false
        and .spec.swaps.primary.properties.label == "swap"
        and .spec.swaps.primary.properties."swap.uuid" == "01234567-89ab-cdef-0123-456789abcdef"
        and .spec.swaps.inventory.operation == "rescan"
        and .spec.swaps.inventory.device == "/dev/disk/by-label/swap-inventory"
        and .spec.swaps.targetSizeAlias.operation == "grow"
        and .spec.swaps.targetSizeAlias.targetSize == "12GiB"
        and .spec.swaps.sizeAlias.operation == "grow"
        and .spec.swaps.sizeAlias.size == "10GiB"
        and .spec.swaps.old.operation == "destroy"
        and .spec.swaps.actionOld.action == "destroy"
        and .spec.swaps.destroyed.destroy == true
        and .spec.swaps.destroyed.device == "/dev/disk/by-label/destroyed-swap"
        and .spec.zram.enable == true
        and .spec.zram.operation == "rescan"
        and .spec.zram.swapDevices == 2
        and .spec.zram.memoryPercent == 40
        and .spec.zram.memoryMax == 8589934592
        and .spec.zram.priority == 20
        and .spec.zram.algorithm == "zstd"
        and .spec.zram.properties."zram.compression-ratio-target" == "2.0"
        and .spec.luks.devices.cryptaction.action == "open"
        and .spec.swaps.old.device == "/dev/disk/by-label/old-swap"
        and .spec.luks.devices.cryptroot.device == "/dev/disk/by-partuuid/d024c121-4300-4493-a643-055bc4d5caa7"
        and .spec.luks.devices.cryptroot.name == "cryptroot"
        and .spec.luks.devices.cryptroot.operation == "grow"
        and .spec.luks.devices.cryptroot.desiredSize == "100%"
        and .spec.luks.devices.cryptroot.properties.label == "cryptroot"
        and .spec.luks.devices.cryptroot.properties."luks.subsystem" == "nixos"
        and .spec.luks.devices.cryptTargetSize.operation == "grow"
        and .spec.luks.devices.cryptTargetSize.target == "cryptTargetSizeMapper"
        and .spec.luks.devices.cryptTargetSize.targetSize == "90%"
        and .spec.luks.devices.cryptSize.operation == "grow"
        and .spec.luks.devices.cryptSize.size == "80%"
        and .spec.luks.devices.cryptold.destroy == true
        and .spec.luks.devices.cryptold.device == "/dev/disk/by-partuuid/old-luks"
        and .spec.luks.devices.cryptarchive.operation == "open"
        and .spec.luks.devices.cryptarchive.device == "/dev/disk/by-id/archive-luks"
        and .spec.luks.devices.cryptclosed.operation == "close"
        and .spec.luks.devices.cryptclosed.device == "/dev/disk/by-id/closed-luks"
        and .spec.filesystems.shared.device == "nas.example.com:/srv/shared"
        and .spec.filesystems.shared.mountpoint == "/srv/shared"
        and .spec.filesystems.shared.fsType == "nfs4"
        and (.spec.filesystems.shared.options | index("x-systemd.automount") != null)
        and (.spec.filesystems | has("/srv/old") | not)
        and .spec.nfs.mounts.shared.source == "nas.example.com:/srv/shared"
        and .spec.nfs.mounts.shared.mountpoint == "/srv/shared"
        and .spec.nfs.mounts.shared.operation == "mount"
        and .spec.nfs.mounts.shared.metadata.server == "nas.example.com"
        and .spec.nfs.mounts.shared.metadata.export == "/srv/shared"
        and .spec.nfs.mounts."/srv/tuned".operation == "remount"
        and (.spec.nfs.mounts."/srv/tuned".options | index("ro") != null)
        and .spec.nfs.mounts."/srv/action".action == "remount"
        and .spec.nfs.mounts."/srv/inventory".operation == "rescan"
        and .spec.nfs.mounts."/srv/inventory".source == "nas.example.com:/srv/inventory"
        and .spec.nfs.mounts."/srv/old".source == "nas.example.com:/srv/old"
        and .spec.nfs.mounts."/srv/old".operation == "unmount"
        and .spec.iscsi.initiatorName == "iqn.2026-06.example:host"
        and (.spec.iscsi | has("discoverPortal") | not)
        and (.spec.iscsi.boot | has("discoverPortal") | not)
        and .spec.iscsi.boot.target == "iqn.2026-06.example:storage.root"
        and .spec.iscsi.sessions."iqn.2026-06.example:storage.root".operation == "grow"
        and .spec.iscsi.sessions."iqn.2026-06.example:storage.root".desiredSize == "2TiB"
        and .spec.iscsi.sessions."iqn.2026-06.example:storage.alias".targetSize == "3TiB"
        and .spec.iscsi.sessions."iqn.2026-06.example:storage.login".operation == "login"
        and .spec.iscsi.sessions."iqn.2026-06.example:storage.logout".operation == "logout"
        and .spec.iscsi.sessions."iqn.2026-06.example:storage.rescan".operation == "rescan"
        and .spec.iscsiSessions."iqn.2026-06.example:storage.root".portal == "192.0.2.10:3260"
        and .spec.iscsiSessions."iqn.2026-06.example:storage.root".operation == "grow"
        and .spec.iscsiSessions."iqn.2026-06.example:storage.root".desiredSize == "2TiB"
        and .spec.iscsiSessions."iqn.2026-06.example:storage.alias".targetSize == "3TiB"
        and .spec.iscsiSessions."iqn.2026-06.example:storage.login".operation == "login"
        and .spec.iscsiSessions."iqn.2026-06.example:storage.login".portal == "192.0.2.10:3260"
        and .spec.iscsiSessions."iqn.2026-06.example:storage.logout".operation == "logout"
        and .spec.iscsiSessions."iqn.2026-06.example:storage.logout".portal == "192.0.2.11:3260"
        and .spec.iscsiSessions."iqn.2026-06.example:storage.rescan".operation == "rescan"
        and .spec.iscsiSessions."iqn.2026-06.example:storage.rescan".portal == "192.0.2.10:3260"
        and .spec.luns."iqn.2026-06.example:storage/root:0".lun == 0
        and .spec.luns."iqn.2026-06.example:storage/root:0".device == "/dev/disk/by-path/ip-192.0.2.10:3260-iscsi-iqn.2026-06.example:storage-lun-0"
        and (.spec.luns."iqn.2026-06.example:storage/root:0".devices | index("/dev/disk/by-path/ip-192.0.2.11:3260-iscsi-iqn.2026-06.example:storage-lun-0") != null)
        and .spec.luns."iqn.2026-06.example:storage/new:2".operation == "attach"
        and .spec.luns."iqn.2026-06.example:storage/new:2".device == "/dev/disk/by-path/ip-192.0.2.10:3260-iscsi-iqn.2026-06.example:storage-lun-2"
        and .spec.luns."iqn.2026-06.example:storage/old:3".operation == "detach"
        and (.spec.luns."iqn.2026-06.example:storage/old:3".devices | index("/dev/disk/by-path/ip-192.0.2.11:3260-iscsi-iqn.2026-06.example:storage-lun-3") != null)
        and .spec.luns."iqn.2026-06.example:storage/rescan:4".operation == "rescan"
        and (.spec.luns."iqn.2026-06.example:storage/rescan:4".paths | index("/dev/disk/by-path/ip-192.0.2.10:3260-iscsi-iqn.2026-06.example:storage-lun-4") != null)
        and .spec.nvmeNamespaces.rootNamespace.operation == "create"
        and .spec.nvmeNamespaces.rootNamespace.path == "/dev/nvme0"
        and .spec.nvmeNamespaces.rootNamespace.desiredSize == "100G"
        and .spec.nvmeNamespaces.rootNamespace.namespaceId == "4"
        and .spec.nvmeNamespaces.rootNamespace.controllers == "0x1"
        and .spec.nvmeNamespaces."/dev/nvme1".operation == "rescan"
        and .spec.nvmeNamespaces."/dev/nvme2".nsid == "7"
        and .spec.nvmeNamespaces."/dev/nvme2".controllerId == "0x2"
        and .spec.nvmeNamespaces."/dev/nvme3".namespaceId == "8"
        and .spec.nvmeNamespaces."/dev/nvme3".controller == "0x3"
        and .spec.exports.share.operation == "export"
        and .spec.exports.share.path == "/srv/share"
        and .spec.exports.share.client == "192.0.2.0/24"
        and .spec.exports.share.options == "rw,sync,no_subtree_check"
        and .spec.exports."/srv/inventory".operation == "rescan"
        and .spec.exports."/srv/old-share".operation == "unexport"
        and .spec.exports."/srv/old-share".client == "192.0.2.55"
        and .spec.partitions.root.operation == "grow"
        and .spec.partitions.root.device == "/dev/disk/by-id/nvme-root"
        and .spec.partitions.root.number == "2"
        and .spec.partitions.root.endOffset == "100%"
        and .spec.partitions.dataTable.operation == "rescan"
        and .spec.partitions.dataTable.device == "/dev/disk/by-id/nvme-data"
        and .spec.btrfsSubvolumes."/mnt/persist/@home".operation == "create"
        and .spec.btrfsSubvolumes."/mnt/persist/@home".path == "/mnt/persist/@home"
        and .spec.btrfsSubvolumes."/mnt/persist/@inventory".operation == "rescan"
        and .spec.btrfsSubvolumes."/mnt/persist/@inventory".path == "/mnt/persist/@inventory"
        and .spec.btrfsSubvolumes."/mnt/persist/@old-name".operation == "rename"
        and .spec.btrfsSubvolumes."/mnt/persist/@old-name".renameTo == "/mnt/persist/@new-name"
        and .spec.btrfsQgroups."0/257".target == "/mnt/persist"
        and .spec.btrfsQgroups."0/257".properties.limit == "25GiB"
        and .spec.btrfsQgroups."0/258".operation == "rescan"
        and .spec.btrfsQgroups."0/258".target == "/mnt/persist"
        and .spec.volumes.scratch.operation == "create"
        and .spec.volumes.scratch.target == "vg0/scratch"
        and .spec.volumes.scratch.desiredSize == "10GiB"
        and .spec.volumes."vg0/size-alias".size == "12GiB"
        and .spec.volumes."vg0/reporting".operation == "rescan"
        and .spec.datasets."tank/home".operation == "create"
        and .spec.datasets."tank/inventory".operation == "rescan"
        and .spec.vdoVolumes.archiveLifecycle.target == "archive"
        and .spec.vdoVolumes.archiveLifecycle.operation == "grow"
        and .spec.vdoVolumes.archiveLifecycle.desiredSize == "4TiB"
        and .spec.vdoVolumes.archiveLifecycle.physicalSize == "6TiB"
        and .spec.vdoVolumes.archiveLifecycle.properties.writePolicy == "sync"
        and .spec.vdoVolumes.archiveLifecycle.properties.compression == "enabled"
        and .spec.vdoVolumes.archiveLifecycle.properties.deduplication == "disabled"
        and .spec.vdoVolumes.warmArchive.target == "warm-archive"
        and .spec.vdoVolumes.warmArchive.operation == "start"
        and .spec.vdoVolumes.coldArchive.target == "cold-archive"
        and .spec.vdoVolumes.coldArchive.operation == "stop"
        and .spec.vdoVolumes.refreshArchive.target == "refresh-archive"
        and .spec.vdoVolumes.refreshArchive.operation == "rescan"
        and .spec.physicalVolumes.nvmePvGrow.operation == "grow"
        and .spec.physicalVolumes.nvmePvGrow.path == "/dev/disk/by-id/nvme-pv-grow"
        and .spec.physicalVolumes."/dev/disk/by-id/nvme-pv-refresh".operation == "rescan"
        and .spec.luksKeyslots."cryptroot:1".operation == "add-key"
        and .spec.luksKeyslots."cryptroot:1".device == "/dev/disk/by-id/root-luks"
        and .spec.luksKeyslots."cryptroot:1".keySlot == "1"
        and .spec.luksKeyslots."cryptroot:1".newKeyFile == "/run/keys/root-new"
        and .spec.luksKeyslots."cryptroot:2".operation == "remove-key"
        and .spec.luksKeyslots."cryptroot:2".device == "/dev/disk/by-id/root-luks"
        and .spec.luksKeyslots."cryptroot:2".keySlot == "2"
        and .spec.luksKeyslots."cryptroot:3"."key-slot" == "3"
        and .spec.luksKeyslots."cryptroot:3"."new-key-file" == "/run/keys/root-new-alias"
        and .spec.luksKeyslots."cryptroot:4".slot == "4"
        and .spec.luksTokens."cryptroot:0".operation == "import-token"
        and .spec.luksTokens."cryptroot:0".device == "/dev/disk/by-id/root-luks"
        and .spec.luksTokens."cryptroot:0".tokenId == "0"
        and .spec.luksTokens."cryptroot:0".tokenFile == "/run/keys/root-token.json"
        and .spec.luksTokens."cryptroot:1".operation == "remove-token"
        and .spec.luksTokens."cryptroot:1".device == "/dev/disk/by-id/root-luks"
        and .spec.luksTokens."cryptroot:1".tokenId == "1"
        and .spec.luksTokens."cryptroot:2".token == "2"
        and .spec.luksTokens."cryptroot:2"."token-file" == "/run/keys/root-token-alias.json"
        and .spec.luksTokens."cryptroot:3"."token-id" == "3"
        and .spec.zvols."tank/vm/root".operation == "grow"
        and .spec.zvols."tank/vm/root".desiredSize == "80GiB"
        and .spec.zvols."tank/vm/inventory".operation == "rescan"
        and .spec.thinPools.primaryPool.operation == "grow"
        and .spec.thinPools.primaryPool.path == "vg0/thinpool"
        and .spec.thinPools.primaryPool.desiredSize == "500GiB"
        and .spec.thinPools."vg0/newthin".operation == "create"
        and .spec.thinPools."vg0/newthin".desiredSize == "100GiB"
        and .spec.thinPools."vg0/reporting".operation == "rescan"
        and .spec.lvmSnapshots."vg0/root-snap".operation == "snapshot"
        and .spec.lvmSnapshots."vg0/root-snap".target == "vg0/root"
        and .spec.lvmSnapshots."vg0/root-snap".desiredSize == "20GiB"
        and .spec.lvmSnapshots."vg0/root-inspect".operation == "rescan"
        and .spec.lvmCaches."vg0/root".operation == "create"
        and .spec.lvmCaches."vg0/root".device == "vg0/root-cache"
        and .spec.lvmCaches."vg0/root".properties."lvm.cache-mode" == "writethrough"
        and .spec.lvmCaches."vg0/archive".operation == "rescan"
        and .spec.volumes."vg0/archive".operation == "deactivate"
        and .spec.loopDevices.rootImage.operation == "create"
        and .spec.loopDevices.rootImage.path == "/dev/loop7"
        and .spec.loopDevices.rootImage.device == "/var/lib/images/root.img"
        and .spec.loopDevices."/dev/loop10".operation == "rescan"
        and .spec.backingFiles."/var/lib/images/new.img".operation == "create"
        and .spec.backingFiles."/var/lib/images/new.img".desiredSize == "8GiB"
        and .spec.backingFiles."/var/lib/images/root.img".operation == "grow"
        and .spec.backingFiles."/var/lib/images/root.img".desiredSize == "16GiB"
        and .spec.backingFiles.inventoryImage.operation == "rescan"
        and .spec.backingFiles.inventoryImage.path == "/var/lib/images/inventory.img"
        and .spec.dmMaps.cryptroot.operation == "rescan"
        and .spec.dmMaps.cryptroot.target == "/dev/mapper/cryptroot"
        and .spec.dmMaps.cryptswap.operation == "rename"
        and .spec.dmMaps.cryptswap.target == "/dev/mapper/cryptswap"
        and .spec.dmMaps.cryptswap.renameTo == "cryptswap-retired"
        and .spec.dmMaps.oldmap.operation == "destroy"
        and .spec.dmMaps.oldmap.target == "/dev/mapper/oldmap"
        and .spec.mdRaids.root.target == "/dev/md/root"
        and .spec.mdRaids.root.raidLevel == "1"
        and (.spec.mdRaids.root.devices | index("/dev/disk/by-id/nvme-md-a") != null)
        and (.spec.mdRaids.root.devices | index("/dev/disk/by-id/nvme-md-b") != null)
        and (.spec.mdRaids.root.addDevices | index("/dev/disk/by-id/nvme-md-spare") != null)
        and .spec.mdRaids.root.replaceDevices."/dev/disk/by-id/nvme-md-aging" == "/dev/disk/by-id/nvme-md-replacement"
        and .spec.mdRaids.existing.operation == "assemble"
        and .spec.mdRaids.existing.target == "/dev/md/existing"
        and (.spec.mdRaids.existing.devices | index("/dev/disk/by-id/existing-md-a") != null)
        and .spec.mdRaids.oldroot.operation == "stop"
        and .spec.mdRaids.oldroot.target == "/dev/md/oldroot"
        and .spec.mdRaids.inventory.operation == "rescan"
        and .spec.multipathMaps.mpatha.target == "mpatha"
        and (.spec.multipathMaps.mpatha.addDevices | index("/dev/sdb") != null)
        and .spec.multipathMaps.mpatha.replaceDevices."/dev/sdc" == "/dev/sdd"
        and .spec.multipathMaps.mpathb.operation == "rescan"
        and .spec.multipathMaps.mpathb.target == "mpathb"
        and .spec.multipathMaps.mpathOld.operation == "destroy"
        and .spec.multipathMaps.mpathOld.target == "mpath-old"
        and .spec.caches."tank/l2arc0".cacheSetUuid == "11111111-2222-3333-4444-555555555555"
        and (.spec.caches."/dev/bcache0".addDevices | index("cache-set-uuid") != null)
        and .spec.caches."/dev/bcache0".cacheSetUuid == "cache-set-uuid"
        and .spec.caches."/dev/bcache0".operation == "rescan"
        and .spec.caches."/dev/bcache0".properties."bcache.cache-mode" == "writethrough"
        and .spec.caches."/dev/bcache0".properties."bcache.set-journal-delay-ms" == "100"
        and .spec.pools.vault.operation == "import"
        and .spec.pools.vault.readOnly == true
        and .spec.pools.archiveImport.readonly == true
        and .spec.pools.moveme.operation == "export"
        and .spec.volumeGroups.importvg.operation == "import"
        and .spec.volumeGroups.exportvg.operation == "export"
        and .spec.volumeGroups.activevg.operation == "activate"
        and .spec.volumeGroups.refreshvg.operation == "rescan"
        and .spec.volumeGroups.actionvg.action == "rescan"
        and .spec.datasets."tank/home-review".operation == "promote"
        and .spec.datasets."tank/legacy-alias".renameTarget == "tank/legacy-alias-staged"
        and .spec.datasets."tank/legacy-short".newName == "tank/legacy-short-staged"
        and .spec.snapshots."tank/home@before-upgrade".target == "tank/home"
        and .spec.snapshots."tank/home@before-upgrade".hold == "disk-nix-retain"
        and .spec.snapshots."tank/home@before-upgrade".rollback == true
    and .spec.snapshots."tank/home@before-upgrade".cloneTo == "tank/home-review"
    and .spec.snapshots."tank/home@before-upgrade".renameTo == "tank/home@before-upgrade-retained"
    and .spec.snapshots."tank/home@before-upgrade".recursiveRollback == true
    and .spec.snapshots."tank/home@clone-only".operation == "clone"
    and .spec.snapshots."tank/home@clone-only".cloneTo == "tank/home-clone"
    and .spec.snapshots."tank/home@action-rescan".action == "rescan"
    and .spec.snapshots.aliases.operation == "clone"
    and .spec.snapshots.aliases."snapshot-path" == "tank/home@alias-source"
    and .spec.snapshots.aliases.cloneTarget == "tank/home-alias-clone"
    and .spec.snapshots.aliases.clone == "tank/home-short-clone"
    and .spec.snapshots.aliases.renameTarget == "tank/home@alias-retained"
    and .spec.snapshots.aliases.newName == "tank/home@alias-new"
    and .spec.snapshots.aliases.recursive == true
    and .spec.snapshots.aliases."zfs.rollbackRecursive" == true
    and .spec.snapshots.aliases.readonly == true
    and .spec.datasets."tank/legacy".renameTo == "tank/legacy-staged"
        and .spec.snapshots."tank/home@old".releaseHold == "old-retention"
        and .spec.snapshots."/mnt/persist/@home-before-upgrade".target == "/mnt/persist/@home"
        and .spec.snapshots."/mnt/persist/@home-before-upgrade".readOnly == true
        and .spec.snapshots."/mnt/persist/@home-before-clone".target == "/mnt/persist/@home"
        and .spec.snapshots."/mnt/persist/@home-before-clone".cloneTo == "/mnt/persist/@home-review"
        and .spec.snapshots."/mnt/persist/@home-before-clone".readOnly == true
        and .spec.snapshots."tank/home@inventory".operation == "rescan"
        and .spec.snapshots."/mnt/persist/@home-inventory".operation == "rescan"
        and .spec.snapshots."/mnt/persist/@home-inventory".readOnly == true
        and .spec.snapshots."home-before-friendly".operation == "rescan"
        and .spec.snapshots."home-before-friendly".target == "/mnt/persist/@home"
        and .spec.snapshots."home-before-friendly".snapshotPath == "/mnt/persist/@home-before-friendly"
        and .apply.mode == "activation"
        and .apply.allowGrow == true
        and .apply.allowOffline == false
        and .apply.probeCurrent == true
        and .apply.allowDeviceReplacement == true
        and .apply.allowRebalance == true
        and .apply.allowPotentialDataLoss == false
        and .apply.requireBackup == false
        and .apply.backupVerified == false
        and .apply.requireConfirmation == false
        and .apply.confirmation == false
        and .apply.requireConfirmationFile == "/run/disk-nix/confirm"
        and .apply.failOnBlocked == false
        and .apply.scriptOut == "/run/disk-nix/apply.sh"
        and .apply.reportOut == "/run/disk-nix/apply-report.json"
        and .apply.receiptOut == "/run/disk-nix/apply-receipt.json"
      ' "$spec"
  touch "$out"
''
