const BCACHE_DETAIL_KEYS: &[(&str, &str)] = &[
        ("bcache.role", "role"),
        ("bcache.kind", "kind"),
        ("bcache.backing-device", "backing-device"),
        ("bcache.set-uuid", "set-uuid"),
        ("bcache.set-average-key-size", "set-average-key-size"),
        ("bcache.set-btree-cache-size", "set-btree-cache-size"),
        (
            "bcache.set-cache-available-percent",
            "set-available-percent",
        ),
        ("bcache.set-congested", "set-congested"),
        (
            "bcache.set-congested-read-threshold-us",
            "set-congested-read-us",
        ),
        (
            "bcache.set-congested-write-threshold-us",
            "set-congested-write-us",
        ),
        ("bcache.set-io-error-halflife", "set-io-error-halflife"),
        ("bcache.set-io-error-limit", "set-io-error-limit"),
        ("bcache.set-journal-delay-ms", "set-journal-delay-ms"),
        ("bcache.set-root-usage-percent", "set-root-usage-percent"),
        ("bcache.label", "label"),
        ("bcache.state", "state"),
        ("bcache.running", "running"),
        ("bcache.cache-available-percent", "available-percent"),
        ("bcache.cache-mode", "cache-mode"),
        ("bcache.cache-replacement-policy", "replacement"),
        ("bcache.congested-read-threshold-us", "congested-read-us"),
        ("bcache.congested-write-threshold-us", "congested-write-us"),
        ("bcache.discard", "discard"),
        ("bcache.dirty-data", "dirty"),
        ("bcache.io-errors", "io-errors"),
        ("bcache.metadata-written", "metadata-written"),
        ("bcache.priority-stats", "priority-stats"),
        ("bcache.readahead", "readahead"),
        ("bcache.sequential-cutoff", "sequential-cutoff"),
        ("bcache.written", "written"),
        ("bcache.writeback-delay", "writeback-delay"),
        ("bcache.writeback-metadata", "writeback-metadata"),
        ("bcache.writeback-percent", "writeback-percent"),
        ("bcache.writeback-rate", "writeback-rate"),
        ("bcache.writeback-rate-debug", "writeback-rate-debug"),
        ("bcache.writeback-rate-d-term", "writeback-rate-d-term"),
        (
            "bcache.writeback-rate-i-term-inverse",
            "writeback-rate-i-inverse",
        ),
        ("bcache.writeback-rate-minimum", "writeback-rate-min"),
        (
            "bcache.writeback-rate-p-term-inverse",
            "writeback-rate-p-inverse",
        ),
        (
            "bcache.writeback-rate-update-seconds",
            "writeback-rate-update",
        ),
        ("bcache.writeback-running", "writeback-running"),
];
