const DEVICE_MAPPER_DETAIL_KEYS: &[(&str, &str)] = &[
        ("dm.name", "dm-name"),
        ("dm.uuid", "dm-uuid"),
        ("dm.major", "dm-major"),
        ("dm.minor", "dm-minor"),
        ("dm.open-count", "open"),
        ("dm.segments", "segments"),
        ("dm.events", "events"),
        ("dm.table.targets", "dm-table-targets"),
        ("dm.table.segment-count", "dm-table-segments"),
        ("dm.table.segment.0.start", "dm-table-start"),
        ("dm.table.segment.0.length", "dm-table-length"),
        ("dm.table.segment.0.target", "dm-table-target"),
        ("dm.table.segment.0.payload", "dm-table-payload"),
        ("dm.table.segment.0.device", "dm-table-device"),
        ("dm.table.segment.0.offset", "dm-table-offset"),
        (
            "dm.table.segment.0.metadata-device",
            "dm-table-metadata-device",
        ),
        ("dm.table.segment.0.data-device", "dm-table-data-device"),
        (
            "dm.table.segment.0.data-block-size",
            "dm-table-data-block-size",
        ),
        (
            "dm.table.segment.0.low-water-mark",
            "dm-table-low-water-mark",
        ),
        ("dm.table.segment.0.pool-device", "dm-table-pool-device"),
        ("dm.table.segment.0.thin-device-id", "dm-table-thin-id"),
        (
            "dm.table.segment.0.external-origin-device",
            "dm-table-external-origin",
        ),
        ("dm.table.segment.0.cache-device", "dm-table-cache-device"),
        ("dm.table.segment.0.origin-device", "dm-table-origin-device"),
        ("dm.table.segment.0.block-size", "dm-table-block-size"),
        ("dm.table.segment.0.cow-device", "dm-table-cow-device"),
        ("dm.table.segment.0.persistence", "dm-table-persistence"),
        ("dm.table.segment.0.chunk-size", "dm-table-chunk-size"),
        ("dm.table.segment.0.stripe-count", "dm-table-stripes"),
        (
            "dm.table.segment.0.stripe.0.device",
            "dm-table-stripe0-device",
        ),
        (
            "dm.table.segment.0.stripe.0.offset",
            "dm-table-stripe0-offset",
        ),
        (
            "dm.table.segment.0.stripe.1.device",
            "dm-table-stripe1-device",
        ),
        (
            "dm.table.segment.0.stripe.1.offset",
            "dm-table-stripe1-offset",
        ),
        ("dm.table.segment.0.crypt.cipher", "dm-crypt-cipher"),
        ("dm.table.segment.0.crypt.iv-offset", "dm-crypt-iv-offset"),
        ("dm.table.segment.0.crypt.device", "dm-crypt-device"),
        ("dm.table.segment.0.crypt.offset", "dm-crypt-offset"),
        ("dm.status.targets", "dm-status-targets"),
        ("dm.status.segment-count", "dm-status-segments"),
        ("dm.status.segment.0.start", "dm-status-start"),
        ("dm.status.segment.0.length", "dm-status-length"),
        ("dm.status.segment.0.target", "dm-status-target"),
        ("dm.status.segment.0.payload", "dm-status-payload"),
        (
            "dm.status.segment.0.metadata-used-blocks",
            "dm-status-metadata-used",
        ),
        (
            "dm.status.segment.0.metadata-total-blocks",
            "dm-status-metadata-total",
        ),
        (
            "dm.status.segment.0.cache-used-blocks",
            "dm-status-cache-used",
        ),
        (
            "dm.status.segment.0.cache-total-blocks",
            "dm-status-cache-total",
        ),
        (
            "dm.status.segment.0.data-used-blocks",
            "dm-status-data-used",
        ),
        (
            "dm.status.segment.0.data-total-blocks",
            "dm-status-data-total",
        ),
        ("dm.status.segment.0.read-hits", "dm-status-read-hits"),
        ("dm.status.segment.0.read-misses", "dm-status-read-misses"),
        ("dm.status.segment.0.write-hits", "dm-status-write-hits"),
        ("dm.status.segment.0.write-misses", "dm-status-write-misses"),
        ("dm.status.segment.0.dirty-blocks", "dm-status-dirty"),
        ("dm.status.segment.0.mode", "dm-status-mode"),
        ("dm.status.segment.0.used-sectors", "dm-status-used-sectors"),
        (
            "dm.status.segment.0.total-sectors",
            "dm-status-total-sectors",
        ),
];
