const ENCRYPTION_DETAIL_KEYS: &[(&str, &str)] = &[
        ("cryptsetup.active", "active"),
        ("cryptsetup.in-use", "in-use"),
        ("cryptsetup.cipher", "cipher"),
        ("cryptsetup.mode", "mode"),
        ("cryptsetup.sector-size", "sector-size"),
        ("cryptsetup.sector-count", "sectors"),
        ("cryptsetup.luks-version", "luks"),
        ("cryptsetup.luks-epoch", "epoch"),
        ("cryptsetup.luks-metadata-area", "metadata-area"),
        ("cryptsetup.luks-keyslots-area", "keyslots-area"),
        ("cryptsetup.luks-subsystem", "subsystem"),
        ("cryptsetup.luks-flags", "flags"),
        ("cryptsetup.luks-keyslot-count", "keyslots"),
        ("cryptsetup.luks-token-count", "tokens"),
        ("cryptsetup.luks-keyslots", "keyslot-ids"),
        ("cryptsetup.luks-tokens", "token-ids"),
        ("cryptsetup.luks-keyslot-0-type", "keyslot-0"),
        ("cryptsetup.luks-keyslot-0-priority", "keyslot-0-priority"),
        ("cryptsetup.luks-keyslot-0-cipher", "keyslot-0-cipher"),
        (
            "cryptsetup.luks-keyslot-0-cipher-key",
            "keyslot-0-cipher-key",
        ),
        ("cryptsetup.luks-keyslot-0-pbkdf", "keyslot-0-pbkdf"),
        ("cryptsetup.luks-keyslot-0-time-cost", "keyslot-0-time"),
        ("cryptsetup.luks-keyslot-0-memory", "keyslot-0-memory"),
        ("cryptsetup.luks-keyslot-0-threads", "keyslot-0-threads"),
        ("cryptsetup.luks-keyslot-0-salt", "keyslot-0-salt"),
        (
            "cryptsetup.luks-keyslot-0-af-stripes",
            "keyslot-0-af-stripes",
        ),
        (
            "cryptsetup.luks-keyslot-0-area-offset",
            "keyslot-0-area-offset",
        ),
        (
            "cryptsetup.luks-keyslot-0-area-length",
            "keyslot-0-area-length",
        ),
        ("cryptsetup.luks-keyslot-0-digest-id", "keyslot-0-digest"),
        ("cryptsetup.luks-keyslot-1-type", "keyslot-1"),
        ("cryptsetup.luks-keyslot-1-priority", "keyslot-1-priority"),
        ("cryptsetup.luks-keyslot-1-cipher", "keyslot-1-cipher"),
        (
            "cryptsetup.luks-keyslot-1-cipher-key",
            "keyslot-1-cipher-key",
        ),
        ("cryptsetup.luks-keyslot-1-pbkdf", "keyslot-1-pbkdf"),
        ("cryptsetup.luks-keyslot-1-time-cost", "keyslot-1-time"),
        ("cryptsetup.luks-keyslot-1-memory", "keyslot-1-memory"),
        ("cryptsetup.luks-keyslot-1-threads", "keyslot-1-threads"),
        ("cryptsetup.luks-keyslot-1-salt", "keyslot-1-salt"),
        (
            "cryptsetup.luks-keyslot-1-af-stripes",
            "keyslot-1-af-stripes",
        ),
        (
            "cryptsetup.luks-keyslot-1-area-offset",
            "keyslot-1-area-offset",
        ),
        (
            "cryptsetup.luks-keyslot-1-area-length",
            "keyslot-1-area-length",
        ),
        ("cryptsetup.luks-keyslot-1-digest-id", "keyslot-1-digest"),
        ("cryptsetup.luks-token-0-type", "token-0"),
        ("cryptsetup.luks-token-0-keyslot", "token-0-keyslot"),
        ("cryptsetup.luks-token-0-keyslots", "token-0-keyslots"),
        ("cryptsetup.luks-token-0-tpm2-pcrs", "token-0-tpm2-pcrs"),
        ("cryptsetup.luks-token-0-tpm2-hash", "token-0-tpm2-hash"),
        ("cryptsetup.luks-token-1-type", "token-1"),
        ("cryptsetup.luks-token-1-keyslot", "token-1-keyslot"),
        ("cryptsetup.luks-token-1-keyslots", "token-1-keyslots"),
        ("cryptsetup.luks-token-1-tpm2-pcrs", "token-1-tpm2-pcrs"),
        ("cryptsetup.luks-token-1-tpm2-hash", "token-1-tpm2-hash"),
        ("cryptsetup.luks-digest-count", "digests"),
        ("cryptsetup.luks-digests", "digest-ids"),
        ("cryptsetup.luks-digest-0-type", "digest-0"),
        ("cryptsetup.luks-digest-0-hash", "digest-0-hash"),
        ("cryptsetup.luks-digest-0-iterations", "digest-0-iterations"),
        ("cryptsetup.luks-digest-0-salt", "digest-0-salt"),
        ("cryptsetup.luks-digest-0-digest", "digest-0-digest"),
        ("cryptsetup.luks-digest-1-type", "digest-1"),
        ("cryptsetup.luks-digest-1-hash", "digest-1-hash"),
        ("cryptsetup.luks-digest-1-iterations", "digest-1-iterations"),
        ("cryptsetup.luks-digest-1-salt", "digest-1-salt"),
        ("cryptsetup.luks-digest-1-digest", "digest-1-digest"),
        ("cryptsetup.luks-data-cipher", "data-cipher"),
        ("cryptsetup.luks-data-offset", "data-offset"),
        ("cryptsetup.luks-data-length", "data-length"),
        ("cryptsetup.luks-data-sector", "data-sector"),
];
