const GENERAL_SMART_DETAIL_KEYS: &[(&str, &str)] = &[
        ("model", "model"),
        ("vendor", "vendor"),
        ("transport", "transport"),
        ("rotational", "rotational"),
        ("md.uuid", "md-uuid"),
        ("scsi.address", "scsi-address"),
        ("scsi.host", "scsi-host"),
        ("scsi.channel", "scsi-channel"),
        ("scsi.target", "scsi-target"),
        ("scsi.lun", "scsi-lun"),
        ("scsi.peripheral-type", "scsi-type"),
        ("scsi.vendor", "scsi-vendor"),
        ("scsi.model", "scsi-model"),
        ("scsi.revision", "scsi-revision"),
        ("scsi.block-device", "scsi-block"),
        ("scsi.generic-device", "scsi-generic"),
        ("scsi.size", "scsi-size"),
        ("scsi.transport", "scsi-transport"),
        ("scsi.unit-name", "scsi-unit"),
        ("scsi.by-id", "scsi-by-id"),
        ("scsi.wwn", "scsi-wwn"),
        ("scsi.state", "scsi-state"),
        ("scsi.queue-depth", "scsi-queue-depth"),
        ("scsi.queue-type", "scsi-queue-type"),
        ("scsi.scsi-level", "scsi-level"),
        ("scsi.timeout", "scsi-timeout"),
        ("smartctl.svn-revision", "smart-svn"),
        ("smartctl.platform", "smart-platform"),
        ("smartctl.exit-status", "smart-exit-status"),
        ("smartctl.device-name", "smart-device-name"),
        ("smartctl.health.passed", "smart-health-passed"),
        ("smartctl.device-type", "smart-device-type"),
        ("smartctl.protocol", "smart-protocol"),
        ("smartctl.model", "smart-model"),
        ("smartctl.model-family", "smart-family"),
        ("smartctl.vendor", "smart-vendor"),
        ("smartctl.product", "smart-product"),
        ("smartctl.revision", "smart-revision"),
        ("smartctl.firmware-version", "smart-firmware"),
        ("smartctl.serial", "smart-serial"),
        ("smartctl.wwn-naa", "smart-wwn-naa"),
        ("smartctl.wwn-oui", "smart-wwn-oui"),
        ("smartctl.wwn-id", "smart-wwn-id"),
        ("smartctl.user-capacity-bytes", "smart-capacity"),
        ("smartctl.logical-block-size", "smart-logical-block"),
        ("smartctl.physical-block-size", "smart-physical-block"),
        ("smartctl.rotation-rate-rpm", "smart-rpm"),
        ("smartctl.form-factor", "smart-form-factor"),
        ("smartctl.sata-version", "sata-version"),
        (
            "smartctl.interface-speed-current",
            "interface-speed-current",
        ),
        ("smartctl.interface-speed-max", "interface-speed-max"),
        ("smartctl.power-on-hours", "smart-power-on-hours"),
        ("smartctl.power-cycle-count", "smart-power-cycles"),
        (
            "smartctl.temperature-current-celsius",
            "smart-temperature-c",
        ),
        (
            "smartctl.temperature-highest-celsius",
            "smart-temperature-highest-c",
        ),
        (
            "smartctl.temperature-lowest-celsius",
            "smart-temperature-lowest-c",
        ),
        (
            "smartctl.offline-data-collection-status",
            "smart-offline-status",
        ),
        ("smartctl.self-test-status", "smart-self-test"),
        ("smartctl.error-log-summary-count", "smart-error-log-count"),
        ("smartctl.self-test-log-count", "smart-self-test-count"),
        ("smartctl.error-logging-supported", "smart-error-logging"),
        ("smartctl.gp-logging-supported", "smart-gp-logging"),
        ("smartctl.sct-capabilities", "smart-sct-capabilities"),
        (
            "smartctl.scsi-grown-defect-list",
            "smart-scsi-grown-defects",
        ),
        (
            "smartctl.attribute.reallocated-sector-ct.raw",
            "reallocated-sectors",
        ),
        (
            "smartctl.attribute.reallocated-sector-ct.value",
            "reallocated-value",
        ),
        (
            "smartctl.attribute.reallocated-sector-ct.worst",
            "reallocated-worst",
        ),
        (
            "smartctl.attribute.reallocated-sector-ct.threshold",
            "reallocated-threshold",
        ),
        (
            "smartctl.attribute.reallocated-sector-ct.when-failed",
            "reallocated-failed",
        ),
        (
            "smartctl.attribute.current-pending-sector.raw",
            "pending-sectors",
        ),
        (
            "smartctl.attribute.current-pending-sector.value",
            "pending-value",
        ),
        (
            "smartctl.attribute.current-pending-sector.worst",
            "pending-worst",
        ),
        (
            "smartctl.attribute.current-pending-sector.threshold",
            "pending-threshold",
        ),
        (
            "smartctl.attribute.current-pending-sector.when-failed",
            "pending-failed",
        ),
        (
            "smartctl.attribute.offline-uncorrectable.raw",
            "offline-uncorrectable",
        ),
        (
            "smartctl.attribute.offline-uncorrectable.value",
            "offline-uncorrectable-value",
        ),
        (
            "smartctl.attribute.offline-uncorrectable.worst",
            "offline-uncorrectable-worst",
        ),
        (
            "smartctl.attribute.offline-uncorrectable.threshold",
            "offline-uncorrectable-threshold",
        ),
        (
            "smartctl.attribute.offline-uncorrectable.when-failed",
            "offline-uncorrectable-failed",
        ),
];
