const NETWORK_DETAIL_KEYS: &[(&str, &str)] = &[
        ("iscsi.target", "target"),
        ("iscsi.portal", "portal"),
        ("iscsi.portal-address", "portal-address"),
        ("iscsi.portal-port", "portal-port"),
        ("iscsi.portal-tpgt", "portal-tpgt"),
        ("iscsi.persistent-portal", "persistent-portal"),
        (
            "iscsi.persistent-portal-address",
            "persistent-portal-address",
        ),
        ("iscsi.persistent-portal-port", "persistent-portal-port"),
        ("iscsi.persistent-portal-tpgt", "persistent-portal-tpgt"),
        ("iscsi.target-portal-group-tag", "tpgt"),
        ("iscsi.connection-state", "connection-state"),
        ("iscsi.session-state", "session-state"),
        ("iscsi.internal-session-state", "internal-session-state"),
        ("iscsi.iface-name", "iface"),
        ("iscsi.iface-transport", "transport"),
        ("iscsi.iface-initiator-name", "initiator"),
        ("iscsi.iface-ip-address", "iface-ip"),
        ("iscsi.iface-netdev", "netdev"),
        ("iscsi.host-number", "host"),
        ("iscsi.host-state", "host-state"),
        ("iscsi.connection-cid", "cid"),
        ("iscsi.connection-detail-state", "connection-detail-state"),
        ("iscsi.connection-local-address", "local-address"),
        ("iscsi.connection-peer-address", "peer-address"),
        ("iscsi.headerdigest", "header-digest"),
        ("iscsi.datadigest", "data-digest"),
        ("iscsi.maxrecvdatasegmentlength", "max-recv-data-segment"),
        ("iscsi.maxxmitdatasegmentlength", "max-xmit-data-segment"),
        ("iscsi.firstburstlength", "first-burst"),
        ("iscsi.maxburstlength", "max-burst"),
        ("iscsi.immediatedata", "immediate-data"),
        ("iscsi.initialr2t", "initial-r2t"),
        ("iscsi.maxoutstandingr2t", "max-outstanding-r2t"),
        ("iscsi.scsi-channel", "scsi-channel"),
        ("iscsi.scsi-id", "scsi-id"),
        ("iscsi.attached-disk", "attached-disk"),
        ("iscsi.attached-disk-state", "attached-disk-state"),
        ("iscsi.node-configured", "configured"),
        ("iscsi.node-portal", "node-portal"),
        ("iscsi.node-portal-address", "node-portal-address"),
        ("iscsi.node-portal-port", "node-portal-port"),
        ("iscsi.node-portal-tpgt", "node-portal-tpgt"),
        ("iscsi.node-persistent-portal", "node-persistent-portal"),
        (
            "iscsi.node-persistent-portal-address",
            "node-persistent-portal-address",
        ),
        (
            "iscsi.node-persistent-portal-port",
            "node-persistent-portal-port",
        ),
        (
            "iscsi.node-persistent-portal-tpgt",
            "node-persistent-portal-tpgt",
        ),
        ("iscsi.node-tpgt", "node-tpgt"),
        ("iscsi.node-iface-name", "node-iface"),
        ("iscsi.node-startup", "startup"),
        ("iscsi.node-leading-login", "leading-login"),
        ("iscsi.node-auth-method", "auth-method"),
        ("iscsi.node-auth-username", "auth-username"),
        ("nfs.source", "source"),
        ("nfs.server", "server"),
        ("nfs.export", "export"),
        ("nfs.export-client", "export-client"),
        ("nfs.exportfs", "exportfs"),
        ("nfs.export-option-rw", "export-rw"),
        ("nfs.export-option-ro", "export-ro"),
        ("nfs.export-option-sync", "export-sync"),
        ("nfs.export-option-async", "export-async"),
        ("nfs.export-option-wdelay", "export-wdelay"),
        ("nfs.export-option-no-wdelay", "export-no-wdelay"),
        ("nfs.export-option-hide", "export-hide"),
        ("nfs.export-option-nohide", "export-nohide"),
        (
            "nfs.export-option-no-subtree-check",
            "export-no-subtree-check",
        ),
        ("nfs.export-option-subtree-check", "export-subtree-check"),
        ("nfs.export-option-sec", "export-sec"),
        ("nfs.export-option-secure", "export-secure"),
        ("nfs.export-option-insecure", "export-insecure"),
        ("nfs.export-option-root-squash", "export-root-squash"),
        ("nfs.export-option-no-root-squash", "export-no-root-squash"),
        ("nfs.export-option-all-squash", "export-all-squash"),
        ("nfs.export-option-no-all-squash", "export-no-all-squash"),
        ("nfs.export-option-fsid", "export-fsid"),
        ("nfs.vers", "vers"),
        ("nfs.proto", "proto"),
        ("nfs.sec", "sec"),
        ("nfs.clientaddr", "clientaddr"),
        ("nfs.addr", "addr"),
        ("nfs.port", "port"),
        ("nfs.mountaddr", "mountaddr"),
        ("nfs.mountvers", "mountvers"),
        ("nfs.mountproto", "mountproto"),
        ("nfs.rsize", "rsize"),
        ("nfs.wsize", "wsize"),
        ("nfs.timeo", "timeo"),
        ("nfs.retrans", "retrans"),
        ("nfs.local-lock", "local-lock"),
        ("nfs.lookupcache", "lookupcache"),
        ("nfs.fsc", "fsc"),
        ("nfs.age", "age"),
        ("nfs.namlen", "namlen"),
        ("nfs.caps", "caps"),
        ("nfs.wtmult", "wtmult"),
        ("nfs.dtsize", "dtsize"),
        ("nfs.bsize", "bsize"),
        ("nfs.flavor", "flavor"),
        ("nfs.pseudoflavor", "pseudoflavor"),
        ("nfs.hard", "hard"),
        ("nfs.soft", "soft"),
        ("nfs.noresvport", "noresvport"),
];
