const NVME_DETAIL_KEYS: &[(&str, &str)] = &[
        ("nvme.generic-path", "generic"),
        ("nvme.model", "nvme-model"),
        ("nvme.product", "product"),
        ("nvme.firmware", "firmware"),
        ("nvme.index", "ns-index"),
        ("nvme.namespace", "namespace"),
        ("nvme.namespace-id", "nsid"),
        ("nvme.namespace-uuid", "ns-uuid"),
        ("nvme.eui64", "eui64"),
        ("nvme.nguid", "nguid"),
        ("nvme.subsystem", "subsystem"),
        ("nvme.subsystem-name", "subsystem-name"),
        ("nvme.subsystem-nqn", "subsystem-nqn"),
        ("nvme.hostnqn", "hostnqn"),
        ("nvme.controller", "controller"),
        ("nvme.address", "address"),
        ("nvme.transport", "transport"),
        ("nvme.traddr", "traddr"),
        ("nvme.trsvcid", "trsvcid"),
        ("nvme.host-traddr", "host-traddr"),
        ("nvme.host-iface", "host-iface"),
        ("nvme.path-state", "path-state"),
        ("nvme.controller-id", "controller-id"),
        ("nvme.namespace-capacity", "namespace-capacity"),
        ("nvme.lba-format", "lba-format"),
        ("nvme.maximum-lba", "max-lba"),
        ("nvme.sector-size", "sector-size"),
        ("nvme.ana-state", "ana-state"),
        ("nvme.formatted-lba-index", "flba-index"),
        ("nvme.formatted-lba-data-size", "flba-data"),
        ("nvme.formatted-lba-metadata-size", "flba-metadata"),
        (
            "nvme.formatted-lba-relative-performance",
            "flba-relative-performance",
        ),
        ("nvme.id-ns.nsze", "nsze"),
        ("nvme.id-ns.ncap", "ncap"),
        ("nvme.id-ns.nuse", "nuse"),
        ("nvme.id-ns.nsfeat", "nsfeat"),
        ("nvme.id-ns.nlbaf", "nlbaf"),
        ("nvme.id-ns.flbas", "flbas"),
        ("nvme.id-ns.mc", "mc"),
        ("nvme.id-ns.dpc", "dpc"),
        ("nvme.id-ns.dps", "dps"),
        ("nvme.id-ns.nmic", "nmic"),
        ("nvme.id-ns.rescap", "rescap"),
        ("nvme.id-ns.fpi", "fpi"),
        ("nvme.id-ns.dlfeat", "dlfeat"),
        ("nvme.id-ns.nawun", "nawun"),
        ("nvme.id-ns.nawupf", "nawupf"),
        ("nvme.id-ns.nacwu", "nacwu"),
        ("nvme.id-ns.nabsn", "nabsn"),
        ("nvme.id-ns.nabo", "nabo"),
        ("nvme.id-ns.nabspf", "nabspf"),
        ("nvme.id-ns.noiob", "noiob"),
        ("nvme.id-ns.nvmcap", "nvmcap"),
        ("nvme.id-ctrl.vid", "vid"),
        ("nvme.id-ctrl.ssvid", "ssvid"),
        ("nvme.id-ctrl.rab", "rab"),
        ("nvme.id-ctrl.ieee", "ieee"),
        ("nvme.id-ctrl.cmic", "cmic"),
        ("nvme.id-ctrl.mdts", "mdts"),
        ("nvme.id-ctrl.version", "version"),
        ("nvme.id-ctrl.controller-type", "controller-type"),
        ("nvme.id-ctrl.oacs", "optional-admin-commands"),
        ("nvme.id-ctrl.fuses", "fused-operations"),
        ("nvme.id-ctrl.fna", "format-nvm-attributes"),
        ("nvme.id-ctrl.awun", "atomic-write-unit-normal"),
        ("nvme.id-ctrl.awupf", "atomic-write-unit-powerfail"),
        ("nvme.id-ctrl.acwu", "atomic-compare-write-unit"),
        ("nvme.id-ctrl.sgls", "sgl-support"),
        ("nvme.id-ctrl.namespace-set-id-max", "namespace-set-id-max"),
        (
            "nvme.id-ctrl.endurance-group-id-max",
            "endurance-group-id-max",
        ),
        ("nvme.id-ctrl.ana-transition-time", "ana-transition-time"),
        ("nvme.id-ctrl.ana-group-max", "ana-group-max"),
        (
            "nvme.id-ctrl.persistent-event-log-size",
            "persistent-event-log-size",
        ),
        ("nvme.id-ctrl.domain-id", "domain-id"),
        (
            "nvme.id-ctrl.warning-composite-temp",
            "warning-composite-temp",
        ),
        (
            "nvme.id-ctrl.critical-composite-temp",
            "critical-composite-temp",
        ),
        (
            "nvme.id-ctrl.minimum-thermal-management-temp",
            "min-thermal-management-temp",
        ),
        (
            "nvme.id-ctrl.maximum-thermal-management-temp",
            "max-thermal-management-temp",
        ),
        ("nvme.id-ctrl.total-nvm-capacity", "total-nvm-capacity"),
        (
            "nvme.id-ctrl.unallocated-nvm-capacity",
            "unallocated-nvm-capacity",
        ),
        ("nvme.id-ctrl.namespace-count", "namespace-count"),
        ("nvme.id-ctrl.oncs", "oncs"),
        ("nvme.id-ctrl.volatile-write-cache", "volatile-write-cache"),
        (
            "nvme.id-ctrl.sanitize-capabilities",
            "sanitize-capabilities",
        ),
        ("nvme.id-ctrl.ana-capabilities", "ana-capabilities"),
        ("nvme.smart.critical-warning", "critical-warning"),
        ("nvme.smart.temperature-kelvin", "temperature-k"),
        (
            "nvme.smart.available-spare-percent",
            "available-spare-percent",
        ),
        (
            "nvme.smart.spare-threshold-percent",
            "spare-threshold-percent",
        ),
        ("nvme.smart.percent-used", "percent-used"),
        ("nvme.smart.data-units-read", "data-units-read"),
        ("nvme.smart.data-units-written", "data-units-written"),
        ("nvme.smart.host-read-commands", "host-read-commands"),
        ("nvme.smart.host-write-commands", "host-write-commands"),
        ("nvme.smart.controller-busy-time", "controller-busy-time"),
        ("nvme.smart.power-cycles", "power-cycles"),
        ("nvme.smart.power-on-hours", "power-on-hours"),
        ("nvme.smart.unsafe-shutdowns", "unsafe-shutdowns"),
        ("nvme.smart.media-errors", "media-errors"),
        ("nvme.smart.error-log-entries", "error-log-entries"),
        ("nvme.smart.warning-temperature-time", "warning-temp-time"),
        (
            "nvme.smart.critical-composite-temperature-time",
            "critical-temp-time",
        ),
        ("nvme.smart.temperature-sensor-1-kelvin", "temp-sensor-1-k"),
        ("nvme.smart.temperature-sensor-2-kelvin", "temp-sensor-2-k"),
        ("nvme.smart.temperature-sensor-3-kelvin", "temp-sensor-3-k"),
        ("nvme.smart.temperature-sensor-4-kelvin", "temp-sensor-4-k"),
        ("nvme.smart.temperature-sensor-5-kelvin", "temp-sensor-5-k"),
        ("nvme.smart.temperature-sensor-6-kelvin", "temp-sensor-6-k"),
        ("nvme.smart.temperature-sensor-7-kelvin", "temp-sensor-7-k"),
        ("nvme.smart.temperature-sensor-8-kelvin", "temp-sensor-8-k"),
        (
            "nvme.smart.thermal-temp1-transition-count",
            "thermal-temp1-transitions",
        ),
        (
            "nvme.smart.thermal-temp2-transition-count",
            "thermal-temp2-transitions",
        ),
        (
            "nvme.smart.thermal-temp1-total-time",
            "thermal-temp1-total-time",
        ),
        (
            "nvme.smart.thermal-temp2-total-time",
            "thermal-temp2-total-time",
        ),
];
