fn parse_operation(value: &str) -> Option<Operation> {
    match value {
        "create" => Some(Operation::Create),
        "format" => Some(Operation::Format),
        "grow" => Some(Operation::Grow),
        "shrink" => Some(Operation::Shrink),
        "check" => Some(Operation::Check),
        "repair" => Some(Operation::Repair),
        "scrub" => Some(Operation::Scrub),
        "trim" => Some(Operation::Trim),
        "rescan" | "re-scan" => Some(Operation::Rescan),
        "replace-device" | "replaceDevice" => Some(Operation::ReplaceDevice),
        "add-device" | "addDevice" => Some(Operation::AddDevice),
        "remove-device" | "removeDevice" => Some(Operation::RemoveDevice),
        "add-key" | "addKey" | "add-keyslot" | "addKeyslot" => Some(Operation::AddKey),
        "remove-key" | "removeKey" | "remove-keyslot" | "removeKeyslot" | "kill-slot"
        | "killSlot" => Some(Operation::RemoveKey),
        "import-token" | "importToken" => Some(Operation::ImportToken),
        "remove-token" | "removeToken" => Some(Operation::RemoveToken),
        "set-property" | "setProperty" => Some(Operation::SetProperty),
        "snapshot" => Some(Operation::Snapshot),
        "clone" => Some(Operation::Clone),
        "promote" => Some(Operation::Promote),
        "import" => Some(Operation::Import),
        "export" => Some(Operation::Export),
        "unexport" | "un-export" => Some(Operation::Unexport),
        "attach" => Some(Operation::Attach),
        "detach" => Some(Operation::Detach),
        "activate" => Some(Operation::Activate),
        "deactivate" => Some(Operation::Deactivate),
        "assemble" => Some(Operation::Assemble),
        "start" => Some(Operation::Start),
        "stop" => Some(Operation::Stop),
        "login" | "log-in" | "logIn" => Some(Operation::Login),
        "logout" | "log-out" | "logOut" => Some(Operation::Logout),
        "open" => Some(Operation::Open),
        "close" => Some(Operation::Close),
        "mount" => Some(Operation::Mount),
        "unmount" | "un-mount" | "umount" => Some(Operation::Unmount),
        "remount" => Some(Operation::Remount),
        "rename" => Some(Operation::Rename),
        "rebalance" => Some(Operation::Rebalance),
        "rollback" => Some(Operation::Rollback),
        "destroy" => Some(Operation::Destroy),
        _ => None,
    }
}

fn operation_id(operation: Operation) -> &'static str {
    match operation {
        Operation::Create => "create",
        Operation::Format => "format",
        Operation::Grow => "grow",
        Operation::Shrink => "shrink",
        Operation::Check => "check",
        Operation::Repair => "repair",
        Operation::Scrub => "scrub",
        Operation::Trim => "trim",
        Operation::Rescan => "rescan",
        Operation::ReplaceDevice => "replace-device",
        Operation::AddDevice => "add-device",
        Operation::RemoveDevice => "remove-device",
        Operation::AddKey => "add-key",
        Operation::RemoveKey => "remove-key",
        Operation::ImportToken => "import-token",
        Operation::RemoveToken => "remove-token",
        Operation::SetProperty => "set-property",
        Operation::Snapshot => "snapshot",
        Operation::Clone => "clone",
        Operation::Promote => "promote",
        Operation::Import => "import",
        Operation::Export => "export",
        Operation::Unexport => "unexport",
        Operation::Attach => "attach",
        Operation::Detach => "detach",
        Operation::Activate => "activate",
        Operation::Deactivate => "deactivate",
        Operation::Assemble => "assemble",
        Operation::Start => "start",
        Operation::Stop => "stop",
        Operation::Login => "login",
        Operation::Logout => "logout",
        Operation::Open => "open",
        Operation::Close => "close",
        Operation::Mount => "mount",
        Operation::Unmount => "unmount",
        Operation::Remount => "remount",
        Operation::Rename => "rename",
        Operation::Rebalance => "rebalance",
        Operation::Rollback => "rollback",
        Operation::Destroy => "destroy",
    }
}
