name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  flake-check:
    runs-on: ${{ fromJSON(vars.CI_RUNNER_LABELS) }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - name: Check flake
        run: nix flake check
